// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cassy.proto

package scheduler.grpc;

public interface BackupListingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.BackupListingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .rpc.BackupListingResponse.Entry entries = 1;</code>
   */
  java.util.List<scheduler.grpc.BackupListingResponse.Entry>
      getEntriesList();
  /**
   * <code>repeated .rpc.BackupListingResponse.Entry entries = 1;</code>
   */
  scheduler.grpc.BackupListingResponse.Entry getEntries(int index);
  /**
   * <code>repeated .rpc.BackupListingResponse.Entry entries = 1;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .rpc.BackupListingResponse.Entry entries = 1;</code>
   */
  java.util.List<? extends scheduler.grpc.BackupListingResponse.EntryOrBuilder>
      getEntriesOrBuilderList();
  /**
   * <code>repeated .rpc.BackupListingResponse.Entry entries = 1;</code>
   */
  scheduler.grpc.BackupListingResponse.EntryOrBuilder getEntriesOrBuilder(
      int index);
}
