// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cassy.proto

package scheduler.grpc;

public interface ClusterListingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.ClusterListingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .rpc.ClusterListingResponse.Entry entries = 1;</code>
   */
  java.util.List<scheduler.grpc.ClusterListingResponse.Entry>
      getEntriesList();
  /**
   * <code>repeated .rpc.ClusterListingResponse.Entry entries = 1;</code>
   */
  scheduler.grpc.ClusterListingResponse.Entry getEntries(int index);
  /**
   * <code>repeated .rpc.ClusterListingResponse.Entry entries = 1;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .rpc.ClusterListingResponse.Entry entries = 1;</code>
   */
  java.util.List<? extends scheduler.grpc.ClusterListingResponse.EntryOrBuilder>
      getEntriesOrBuilderList();
  /**
   * <code>repeated .rpc.ClusterListingResponse.Entry entries = 1;</code>
   */
  scheduler.grpc.ClusterListingResponse.EntryOrBuilder getEntriesOrBuilder(
      int index);
}
