// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cassy.proto

package scheduler.grpc;

public interface RestoreRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.RestoreRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cluster_id = 1;</code>
   */
  java.lang.String getClusterId();
  /**
   * <code>string cluster_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getClusterIdBytes();

  /**
   * <pre>
   * optional
   * </pre>
   *
   * <code>repeated string target_ips = 2;</code>
   */
  java.util.List<java.lang.String>
      getTargetIpsList();
  /**
   * <pre>
   * optional
   * </pre>
   *
   * <code>repeated string target_ips = 2;</code>
   */
  int getTargetIpsCount();
  /**
   * <pre>
   * optional
   * </pre>
   *
   * <code>repeated string target_ips = 2;</code>
   */
  java.lang.String getTargetIps(int index);
  /**
   * <pre>
   * optional
   * </pre>
   *
   * <code>repeated string target_ips = 2;</code>
   */
  com.google.protobuf.ByteString
      getTargetIpsBytes(int index);

  /**
   * <code>string snapshot_id = 3;</code>
   */
  java.lang.String getSnapshotId();
  /**
   * <code>string snapshot_id = 3;</code>
   */
  com.google.protobuf.ByteString
      getSnapshotIdBytes();

  /**
   * <code>uint32 restore_type = 4;</code>
   */
  int getRestoreType();

  /**
   * <pre>
   * optional (default: false)
   * </pre>
   *
   * <code>bool snapshot_only = 5;</code>
   */
  boolean getSnapshotOnly();
}
