// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cassy.proto

package scheduler.grpc;

public interface RestoreStatusListingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.RestoreStatusListingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cluster_id = 1;</code>
   */
  java.lang.String getClusterId();
  /**
   * <code>string cluster_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getClusterIdBytes();

  /**
   * <code>repeated .rpc.RestoreStatusListingResponse.Entry entries = 3;</code>
   */
  java.util.List<scheduler.grpc.RestoreStatusListingResponse.Entry>
      getEntriesList();
  /**
   * <code>repeated .rpc.RestoreStatusListingResponse.Entry entries = 3;</code>
   */
  scheduler.grpc.RestoreStatusListingResponse.Entry getEntries(int index);
  /**
   * <code>repeated .rpc.RestoreStatusListingResponse.Entry entries = 3;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .rpc.RestoreStatusListingResponse.Entry entries = 3;</code>
   */
  java.util.List<? extends scheduler.grpc.RestoreStatusListingResponse.EntryOrBuilder>
      getEntriesOrBuilderList();
  /**
   * <code>repeated .rpc.RestoreStatusListingResponse.Entry entries = 3;</code>
   */
  scheduler.grpc.RestoreStatusListingResponse.EntryOrBuilder getEntriesOrBuilder(
      int index);
}
