// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cassy.proto

package scheduler.grpc;

/**
 * Protobuf type {@code rpc.RestoreResponse}
 */
public  final class RestoreResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpc.RestoreResponse)
    RestoreResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RestoreResponse.newBuilder() to construct.
  private RestoreResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RestoreResponse() {
    status_ = 0;
    clusterId_ = "";
    targetIps_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    snapshotId_ = "";
    restoreType_ = 0;
    snapshotOnly_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RestoreResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            clusterId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              targetIps_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            targetIps_.add(s);
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            snapshotId_ = s;
            break;
          }
          case 40: {

            restoreType_ = input.readUInt32();
            break;
          }
          case 48: {

            snapshotOnly_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        targetIps_ = targetIps_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return scheduler.grpc.CassyProto.internal_static_rpc_RestoreResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return scheduler.grpc.CassyProto.internal_static_rpc_RestoreResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            scheduler.grpc.RestoreResponse.class, scheduler.grpc.RestoreResponse.Builder.class);
  }

  private int bitField0_;
  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>.rpc.OperationStatus status = 1;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.rpc.OperationStatus status = 1;</code>
   */
  public scheduler.grpc.OperationStatus getStatus() {
    @SuppressWarnings("deprecation")
    scheduler.grpc.OperationStatus result = scheduler.grpc.OperationStatus.valueOf(status_);
    return result == null ? scheduler.grpc.OperationStatus.UNRECOGNIZED : result;
  }

  public static final int CLUSTER_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object clusterId_;
  /**
   * <code>string cluster_id = 2;</code>
   */
  public java.lang.String getClusterId() {
    java.lang.Object ref = clusterId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clusterId_ = s;
      return s;
    }
  }
  /**
   * <code>string cluster_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getClusterIdBytes() {
    java.lang.Object ref = clusterId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clusterId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TARGET_IPS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList targetIps_;
  /**
   * <code>repeated string target_ips = 3;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getTargetIpsList() {
    return targetIps_;
  }
  /**
   * <code>repeated string target_ips = 3;</code>
   */
  public int getTargetIpsCount() {
    return targetIps_.size();
  }
  /**
   * <code>repeated string target_ips = 3;</code>
   */
  public java.lang.String getTargetIps(int index) {
    return targetIps_.get(index);
  }
  /**
   * <code>repeated string target_ips = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTargetIpsBytes(int index) {
    return targetIps_.getByteString(index);
  }

  public static final int SNAPSHOT_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object snapshotId_;
  /**
   * <code>string snapshot_id = 4;</code>
   */
  public java.lang.String getSnapshotId() {
    java.lang.Object ref = snapshotId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      snapshotId_ = s;
      return s;
    }
  }
  /**
   * <code>string snapshot_id = 4;</code>
   */
  public com.google.protobuf.ByteString
      getSnapshotIdBytes() {
    java.lang.Object ref = snapshotId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      snapshotId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESTORE_TYPE_FIELD_NUMBER = 5;
  private int restoreType_;
  /**
   * <code>uint32 restore_type = 5;</code>
   */
  public int getRestoreType() {
    return restoreType_;
  }

  public static final int SNAPSHOT_ONLY_FIELD_NUMBER = 6;
  private boolean snapshotOnly_;
  /**
   * <code>bool snapshot_only = 6;</code>
   */
  public boolean getSnapshotOnly() {
    return snapshotOnly_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != scheduler.grpc.OperationStatus.UNKNOWN.getNumber()) {
      output.writeEnum(1, status_);
    }
    if (!getClusterIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clusterId_);
    }
    for (int i = 0; i < targetIps_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, targetIps_.getRaw(i));
    }
    if (!getSnapshotIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, snapshotId_);
    }
    if (restoreType_ != 0) {
      output.writeUInt32(5, restoreType_);
    }
    if (snapshotOnly_ != false) {
      output.writeBool(6, snapshotOnly_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != scheduler.grpc.OperationStatus.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, status_);
    }
    if (!getClusterIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clusterId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < targetIps_.size(); i++) {
        dataSize += computeStringSizeNoTag(targetIps_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTargetIpsList().size();
    }
    if (!getSnapshotIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, snapshotId_);
    }
    if (restoreType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, restoreType_);
    }
    if (snapshotOnly_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, snapshotOnly_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof scheduler.grpc.RestoreResponse)) {
      return super.equals(obj);
    }
    scheduler.grpc.RestoreResponse other = (scheduler.grpc.RestoreResponse) obj;

    boolean result = true;
    result = result && status_ == other.status_;
    result = result && getClusterId()
        .equals(other.getClusterId());
    result = result && getTargetIpsList()
        .equals(other.getTargetIpsList());
    result = result && getSnapshotId()
        .equals(other.getSnapshotId());
    result = result && (getRestoreType()
        == other.getRestoreType());
    result = result && (getSnapshotOnly()
        == other.getSnapshotOnly());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + CLUSTER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getClusterId().hashCode();
    if (getTargetIpsCount() > 0) {
      hash = (37 * hash) + TARGET_IPS_FIELD_NUMBER;
      hash = (53 * hash) + getTargetIpsList().hashCode();
    }
    hash = (37 * hash) + SNAPSHOT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSnapshotId().hashCode();
    hash = (37 * hash) + RESTORE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getRestoreType();
    hash = (37 * hash) + SNAPSHOT_ONLY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSnapshotOnly());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static scheduler.grpc.RestoreResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static scheduler.grpc.RestoreResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static scheduler.grpc.RestoreResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static scheduler.grpc.RestoreResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static scheduler.grpc.RestoreResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static scheduler.grpc.RestoreResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static scheduler.grpc.RestoreResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static scheduler.grpc.RestoreResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static scheduler.grpc.RestoreResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static scheduler.grpc.RestoreResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static scheduler.grpc.RestoreResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static scheduler.grpc.RestoreResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(scheduler.grpc.RestoreResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rpc.RestoreResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpc.RestoreResponse)
      scheduler.grpc.RestoreResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return scheduler.grpc.CassyProto.internal_static_rpc_RestoreResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return scheduler.grpc.CassyProto.internal_static_rpc_RestoreResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              scheduler.grpc.RestoreResponse.class, scheduler.grpc.RestoreResponse.Builder.class);
    }

    // Construct using scheduler.grpc.RestoreResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      status_ = 0;

      clusterId_ = "";

      targetIps_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      snapshotId_ = "";

      restoreType_ = 0;

      snapshotOnly_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return scheduler.grpc.CassyProto.internal_static_rpc_RestoreResponse_descriptor;
    }

    @java.lang.Override
    public scheduler.grpc.RestoreResponse getDefaultInstanceForType() {
      return scheduler.grpc.RestoreResponse.getDefaultInstance();
    }

    @java.lang.Override
    public scheduler.grpc.RestoreResponse build() {
      scheduler.grpc.RestoreResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public scheduler.grpc.RestoreResponse buildPartial() {
      scheduler.grpc.RestoreResponse result = new scheduler.grpc.RestoreResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.status_ = status_;
      result.clusterId_ = clusterId_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        targetIps_ = targetIps_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.targetIps_ = targetIps_;
      result.snapshotId_ = snapshotId_;
      result.restoreType_ = restoreType_;
      result.snapshotOnly_ = snapshotOnly_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof scheduler.grpc.RestoreResponse) {
        return mergeFrom((scheduler.grpc.RestoreResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(scheduler.grpc.RestoreResponse other) {
      if (other == scheduler.grpc.RestoreResponse.getDefaultInstance()) return this;
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (!other.getClusterId().isEmpty()) {
        clusterId_ = other.clusterId_;
        onChanged();
      }
      if (!other.targetIps_.isEmpty()) {
        if (targetIps_.isEmpty()) {
          targetIps_ = other.targetIps_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureTargetIpsIsMutable();
          targetIps_.addAll(other.targetIps_);
        }
        onChanged();
      }
      if (!other.getSnapshotId().isEmpty()) {
        snapshotId_ = other.snapshotId_;
        onChanged();
      }
      if (other.getRestoreType() != 0) {
        setRestoreType(other.getRestoreType());
      }
      if (other.getSnapshotOnly() != false) {
        setSnapshotOnly(other.getSnapshotOnly());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      scheduler.grpc.RestoreResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (scheduler.grpc.RestoreResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int status_ = 0;
    /**
     * <code>.rpc.OperationStatus status = 1;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.rpc.OperationStatus status = 1;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.rpc.OperationStatus status = 1;</code>
     */
    public scheduler.grpc.OperationStatus getStatus() {
      @SuppressWarnings("deprecation")
      scheduler.grpc.OperationStatus result = scheduler.grpc.OperationStatus.valueOf(status_);
      return result == null ? scheduler.grpc.OperationStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.rpc.OperationStatus status = 1;</code>
     */
    public Builder setStatus(scheduler.grpc.OperationStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }

      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.rpc.OperationStatus status = 1;</code>
     */
    public Builder clearStatus() {

      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object clusterId_ = "";
    /**
     * <code>string cluster_id = 2;</code>
     */
    public java.lang.String getClusterId() {
      java.lang.Object ref = clusterId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clusterId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cluster_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClusterIdBytes() {
      java.lang.Object ref = clusterId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clusterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cluster_id = 2;</code>
     */
    public Builder setClusterId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      clusterId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cluster_id = 2;</code>
     */
    public Builder clearClusterId() {

      clusterId_ = getDefaultInstance().getClusterId();
      onChanged();
      return this;
    }
    /**
     * <code>string cluster_id = 2;</code>
     */
    public Builder setClusterIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      clusterId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList targetIps_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTargetIpsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        targetIps_ = new com.google.protobuf.LazyStringArrayList(targetIps_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string target_ips = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTargetIpsList() {
      return targetIps_.getUnmodifiableView();
    }
    /**
     * <code>repeated string target_ips = 3;</code>
     */
    public int getTargetIpsCount() {
      return targetIps_.size();
    }
    /**
     * <code>repeated string target_ips = 3;</code>
     */
    public java.lang.String getTargetIps(int index) {
      return targetIps_.get(index);
    }
    /**
     * <code>repeated string target_ips = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTargetIpsBytes(int index) {
      return targetIps_.getByteString(index);
    }
    /**
     * <code>repeated string target_ips = 3;</code>
     */
    public Builder setTargetIps(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTargetIpsIsMutable();
      targetIps_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string target_ips = 3;</code>
     */
    public Builder addTargetIps(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTargetIpsIsMutable();
      targetIps_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string target_ips = 3;</code>
     */
    public Builder addAllTargetIps(
        java.lang.Iterable<java.lang.String> values) {
      ensureTargetIpsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, targetIps_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string target_ips = 3;</code>
     */
    public Builder clearTargetIps() {
      targetIps_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string target_ips = 3;</code>
     */
    public Builder addTargetIpsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureTargetIpsIsMutable();
      targetIps_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object snapshotId_ = "";
    /**
     * <code>string snapshot_id = 4;</code>
     */
    public java.lang.String getSnapshotId() {
      java.lang.Object ref = snapshotId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        snapshotId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string snapshot_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSnapshotIdBytes() {
      java.lang.Object ref = snapshotId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        snapshotId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string snapshot_id = 4;</code>
     */
    public Builder setSnapshotId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      snapshotId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string snapshot_id = 4;</code>
     */
    public Builder clearSnapshotId() {

      snapshotId_ = getDefaultInstance().getSnapshotId();
      onChanged();
      return this;
    }
    /**
     * <code>string snapshot_id = 4;</code>
     */
    public Builder setSnapshotIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      snapshotId_ = value;
      onChanged();
      return this;
    }

    private int restoreType_ ;
    /**
     * <code>uint32 restore_type = 5;</code>
     */
    public int getRestoreType() {
      return restoreType_;
    }
    /**
     * <code>uint32 restore_type = 5;</code>
     */
    public Builder setRestoreType(int value) {

      restoreType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 restore_type = 5;</code>
     */
    public Builder clearRestoreType() {

      restoreType_ = 0;
      onChanged();
      return this;
    }

    private boolean snapshotOnly_ ;
    /**
     * <code>bool snapshot_only = 6;</code>
     */
    public boolean getSnapshotOnly() {
      return snapshotOnly_;
    }
    /**
     * <code>bool snapshot_only = 6;</code>
     */
    public Builder setSnapshotOnly(boolean value) {

      snapshotOnly_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool snapshot_only = 6;</code>
     */
    public Builder clearSnapshotOnly() {

      snapshotOnly_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.RestoreResponse)
  }

  // @@protoc_insertion_point(class_scope:rpc.RestoreResponse)
  private static final scheduler.grpc.RestoreResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new scheduler.grpc.RestoreResponse();
  }

  public static scheduler.grpc.RestoreResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RestoreResponse>
      PARSER = new com.google.protobuf.AbstractParser<RestoreResponse>() {
    @java.lang.Override
    public RestoreResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RestoreResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RestoreResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RestoreResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public scheduler.grpc.RestoreResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

