#!/usr/bin/env bash

localhost=127.0.0.1
cassyPort=20051
clusterID='Set your cluster id here'
snapShotID='Set your snapshop id here'
jsonTakeBackup="{\"cluster_id\": \"$clusterID\", \"backup_type\": 2}"
jsonTakeBackupIP="{\"cluster_id\": \"$clusterID\", \"target_ips\": [\"${localhost}\"], \"backup_type\": 2}"
jsonTakeBackupSnapshot="{\"cluster_id\": \"$clusterID\", \"snapshot_id\": \"${snapShotID}\",\"backup_type\": 3}"
counter=1
total=20
while [[ ${counter} -le ${total} ]]
do
echo Loop ${counter} of ${total}
# Register Cluster
grpcurl -plaintext -d '{"cassandra_host": "127.0.0.1"}' ${localhost}:${cassyPort} rpc.Cassy.RegisterCluster
grpcurl -plaintext ${localhost}:${cassyPort} rpc.Cassy.ListClusters

# Backup
grpcurl -plaintext -d "${jsonTakeBackup}" ${localhost}:${cassyPort} rpc.Cassy.TakeBackup
grpcurl -plaintext -d "${jsonTakeBackupIP}" ${localhost}:${cassyPort} rpc.Cassy.TakeBackup
grpcurl -plaintext -d "${jsonTakeBackupSnapshot}" ${localhost}:${cassyPort} rpc.Cassy.TakeBackup > /dev/null 2>&1
#
## List Backup
grpcurl -plaintext -d "{\"limit\": 3, \"cluster_id\": \"${clusterID}\"}" ${localhost}:${cassyPort} rpc.Cassy.ListBackups > /dev/null 2>&1
grpcurl -plaintext -d "{\"snapshot_id\": \"${snapShotID}\", \"restore_type\": 2, \"cluster_id\": \"${clusterID}\"}" ${localhost}:${cassyPort} rpc.Cassy.RestoreBackup > /dev/null 2>&1
grpcurl -plaintext -d "{\"snapshot_id\": \"${snapShotID}\", \"restore_type\": 2, \"cluster_id\": \"${clusterID}\", \"target_ips\": [\"${localhost}\"]}" ${localhost}:${cassyPort} rpc.Cassy.RestoreBackup > /dev/null 2>&1

# List Statuses
grpcurl -plaintext -d '{"limit": 3, "cluster_id": "Test Cluster-08598f37-4220-41a9-9fe5-97b288c62770"}' ${localhost}:${cassyPort} rpc.Cassy.ListRestoreStatuses > /dev/null 2>&1
((counter++))
done

