// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/main/proto/cassandra-backup.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BackupStatus int32

const (
	BackupStatus_UNKNOWN   BackupStatus = 0
	BackupStatus_STARTED   BackupStatus = 1
	BackupStatus_COMPLETED BackupStatus = 2
	BackupStatus_FAILED    BackupStatus = 3
)

var BackupStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "STARTED",
	2: "COMPLETED",
	3: "FAILED",
}

var BackupStatus_value = map[string]int32{
	"UNKNOWN":   0,
	"STARTED":   1,
	"COMPLETED": 2,
	"FAILED":    3,
}

func (x BackupStatus) String() string {
	return proto.EnumName(BackupStatus_name, int32(x))
}

func (BackupStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{0}
}

type NodeListingResponse_Entry_NodeStatus int32

const (
	NodeListingResponse_Entry_UNKNOWN     NodeListingResponse_Entry_NodeStatus = 0
	NodeListingResponse_Entry_LIVE        NodeListingResponse_Entry_NodeStatus = 1
	NodeListingResponse_Entry_LEAVING     NodeListingResponse_Entry_NodeStatus = 2
	NodeListingResponse_Entry_MOVING      NodeListingResponse_Entry_NodeStatus = 3
	NodeListingResponse_Entry_JOINING     NodeListingResponse_Entry_NodeStatus = 4
	NodeListingResponse_Entry_UNREACHABLE NodeListingResponse_Entry_NodeStatus = 5
)

var NodeListingResponse_Entry_NodeStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "LIVE",
	2: "LEAVING",
	3: "MOVING",
	4: "JOINING",
	5: "UNREACHABLE",
}

var NodeListingResponse_Entry_NodeStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"LIVE":        1,
	"LEAVING":     2,
	"MOVING":      3,
	"JOINING":     4,
	"UNREACHABLE": 5,
}

func (x NodeListingResponse_Entry_NodeStatus) String() string {
	return proto.EnumName(NodeListingResponse_Entry_NodeStatus_name, int32(x))
}

func (NodeListingResponse_Entry_NodeStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{2, 0, 0}
}

type ClusterListingResponse struct {
	ClusterId            []string `protobuf:"bytes,1,rep,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterListingResponse) Reset()         { *m = ClusterListingResponse{} }
func (m *ClusterListingResponse) String() string { return proto.CompactTextString(m) }
func (*ClusterListingResponse) ProtoMessage()    {}
func (*ClusterListingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{0}
}

func (m *ClusterListingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterListingResponse.Unmarshal(m, b)
}
func (m *ClusterListingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterListingResponse.Marshal(b, m, deterministic)
}
func (m *ClusterListingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterListingResponse.Merge(m, src)
}
func (m *ClusterListingResponse) XXX_Size() int {
	return xxx_messageInfo_ClusterListingResponse.Size(m)
}
func (m *ClusterListingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterListingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterListingResponse proto.InternalMessageInfo

func (m *ClusterListingResponse) GetClusterId() []string {
	if m != nil {
		return m.ClusterId
	}
	return nil
}

type NodeListingRequest struct {
	ClusterId            string   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeListingRequest) Reset()         { *m = NodeListingRequest{} }
func (m *NodeListingRequest) String() string { return proto.CompactTextString(m) }
func (*NodeListingRequest) ProtoMessage()    {}
func (*NodeListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{1}
}

func (m *NodeListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeListingRequest.Unmarshal(m, b)
}
func (m *NodeListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeListingRequest.Marshal(b, m, deterministic)
}
func (m *NodeListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeListingRequest.Merge(m, src)
}
func (m *NodeListingRequest) XXX_Size() int {
	return xxx_messageInfo_NodeListingRequest.Size(m)
}
func (m *NodeListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeListingRequest proto.InternalMessageInfo

func (m *NodeListingRequest) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

type NodeListingResponse struct {
	Entries              []*NodeListingResponse_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *NodeListingResponse) Reset()         { *m = NodeListingResponse{} }
func (m *NodeListingResponse) String() string { return proto.CompactTextString(m) }
func (*NodeListingResponse) ProtoMessage()    {}
func (*NodeListingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{2}
}

func (m *NodeListingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeListingResponse.Unmarshal(m, b)
}
func (m *NodeListingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeListingResponse.Marshal(b, m, deterministic)
}
func (m *NodeListingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeListingResponse.Merge(m, src)
}
func (m *NodeListingResponse) XXX_Size() int {
	return xxx_messageInfo_NodeListingResponse.Size(m)
}
func (m *NodeListingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeListingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeListingResponse proto.InternalMessageInfo

func (m *NodeListingResponse) GetEntries() []*NodeListingResponse_Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type NodeListingResponse_Entry struct {
	Ip                   string                               `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Status               NodeListingResponse_Entry_NodeStatus `protobuf:"varint,2,opt,name=status,proto3,enum=rpc.NodeListingResponse_Entry_NodeStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *NodeListingResponse_Entry) Reset()         { *m = NodeListingResponse_Entry{} }
func (m *NodeListingResponse_Entry) String() string { return proto.CompactTextString(m) }
func (*NodeListingResponse_Entry) ProtoMessage()    {}
func (*NodeListingResponse_Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{2, 0}
}

func (m *NodeListingResponse_Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeListingResponse_Entry.Unmarshal(m, b)
}
func (m *NodeListingResponse_Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeListingResponse_Entry.Marshal(b, m, deterministic)
}
func (m *NodeListingResponse_Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeListingResponse_Entry.Merge(m, src)
}
func (m *NodeListingResponse_Entry) XXX_Size() int {
	return xxx_messageInfo_NodeListingResponse_Entry.Size(m)
}
func (m *NodeListingResponse_Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeListingResponse_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_NodeListingResponse_Entry proto.InternalMessageInfo

func (m *NodeListingResponse_Entry) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *NodeListingResponse_Entry) GetStatus() NodeListingResponse_Entry_NodeStatus {
	if m != nil {
		return m.Status
	}
	return NodeListingResponse_Entry_UNKNOWN
}

type BackupListingRequest struct {
	ClusterId            string   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	TargetIp             string   `protobuf:"bytes,2,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	N                    uint32   `protobuf:"varint,3,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupListingRequest) Reset()         { *m = BackupListingRequest{} }
func (m *BackupListingRequest) String() string { return proto.CompactTextString(m) }
func (*BackupListingRequest) ProtoMessage()    {}
func (*BackupListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{3}
}

func (m *BackupListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupListingRequest.Unmarshal(m, b)
}
func (m *BackupListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupListingRequest.Marshal(b, m, deterministic)
}
func (m *BackupListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupListingRequest.Merge(m, src)
}
func (m *BackupListingRequest) XXX_Size() int {
	return xxx_messageInfo_BackupListingRequest.Size(m)
}
func (m *BackupListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackupListingRequest proto.InternalMessageInfo

func (m *BackupListingRequest) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *BackupListingRequest) GetTargetIp() string {
	if m != nil {
		return m.TargetIp
	}
	return ""
}

func (m *BackupListingRequest) GetN() uint32 {
	if m != nil {
		return m.N
	}
	return 0
}

type BackupListingResponse struct {
	Entries              []*BackupListingResponse_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *BackupListingResponse) Reset()         { *m = BackupListingResponse{} }
func (m *BackupListingResponse) String() string { return proto.CompactTextString(m) }
func (*BackupListingResponse) ProtoMessage()    {}
func (*BackupListingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{4}
}

func (m *BackupListingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupListingResponse.Unmarshal(m, b)
}
func (m *BackupListingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupListingResponse.Marshal(b, m, deterministic)
}
func (m *BackupListingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupListingResponse.Merge(m, src)
}
func (m *BackupListingResponse) XXX_Size() int {
	return xxx_messageInfo_BackupListingResponse.Size(m)
}
func (m *BackupListingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupListingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BackupListingResponse proto.InternalMessageInfo

func (m *BackupListingResponse) GetEntries() []*BackupListingResponse_Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type BackupListingResponse_Entry struct {
	SnapshotId           string       `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	BackupId             uint64       `protobuf:"varint,2,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	ClusterId            string       `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	TargetIp             string       `protobuf:"bytes,4,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	BackupType           uint32       `protobuf:"varint,5,opt,name=backup_type,json=backupType,proto3" json:"backup_type,omitempty"`
	Status               BackupStatus `protobuf:"varint,6,opt,name=status,proto3,enum=rpc.BackupStatus" json:"status,omitempty"`
	Timestamp            uint64       `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BackupListingResponse_Entry) Reset()         { *m = BackupListingResponse_Entry{} }
func (m *BackupListingResponse_Entry) String() string { return proto.CompactTextString(m) }
func (*BackupListingResponse_Entry) ProtoMessage()    {}
func (*BackupListingResponse_Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{4, 0}
}

func (m *BackupListingResponse_Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupListingResponse_Entry.Unmarshal(m, b)
}
func (m *BackupListingResponse_Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupListingResponse_Entry.Marshal(b, m, deterministic)
}
func (m *BackupListingResponse_Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupListingResponse_Entry.Merge(m, src)
}
func (m *BackupListingResponse_Entry) XXX_Size() int {
	return xxx_messageInfo_BackupListingResponse_Entry.Size(m)
}
func (m *BackupListingResponse_Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupListingResponse_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_BackupListingResponse_Entry proto.InternalMessageInfo

func (m *BackupListingResponse_Entry) GetSnapshotId() string {
	if m != nil {
		return m.SnapshotId
	}
	return ""
}

func (m *BackupListingResponse_Entry) GetBackupId() uint64 {
	if m != nil {
		return m.BackupId
	}
	return 0
}

func (m *BackupListingResponse_Entry) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *BackupListingResponse_Entry) GetTargetIp() string {
	if m != nil {
		return m.TargetIp
	}
	return ""
}

func (m *BackupListingResponse_Entry) GetBackupType() uint32 {
	if m != nil {
		return m.BackupType
	}
	return 0
}

func (m *BackupListingResponse_Entry) GetStatus() BackupStatus {
	if m != nil {
		return m.Status
	}
	return BackupStatus_UNKNOWN
}

func (m *BackupListingResponse_Entry) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type BackupRequest struct {
	ClusterId            string   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	BackupType           uint32   `protobuf:"varint,2,opt,name=backup_type,json=backupType,proto3" json:"backup_type,omitempty"`
	TargetIp             string   `protobuf:"bytes,3,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	Keyspaces            []string `protobuf:"bytes,4,rep,name=keyspaces,proto3" json:"keyspaces,omitempty"`
	SnapshotId           string   `protobuf:"bytes,5,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupRequest) Reset()         { *m = BackupRequest{} }
func (m *BackupRequest) String() string { return proto.CompactTextString(m) }
func (*BackupRequest) ProtoMessage()    {}
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{5}
}

func (m *BackupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupRequest.Unmarshal(m, b)
}
func (m *BackupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupRequest.Marshal(b, m, deterministic)
}
func (m *BackupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupRequest.Merge(m, src)
}
func (m *BackupRequest) XXX_Size() int {
	return xxx_messageInfo_BackupRequest.Size(m)
}
func (m *BackupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackupRequest proto.InternalMessageInfo

func (m *BackupRequest) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *BackupRequest) GetBackupType() uint32 {
	if m != nil {
		return m.BackupType
	}
	return 0
}

func (m *BackupRequest) GetTargetIp() string {
	if m != nil {
		return m.TargetIp
	}
	return ""
}

func (m *BackupRequest) GetKeyspaces() []string {
	if m != nil {
		return m.Keyspaces
	}
	return nil
}

func (m *BackupRequest) GetSnapshotId() string {
	if m != nil {
		return m.SnapshotId
	}
	return ""
}

type BackupResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	BackupId             uint64   `protobuf:"varint,2,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupResponse) Reset()         { *m = BackupResponse{} }
func (m *BackupResponse) String() string { return proto.CompactTextString(m) }
func (*BackupResponse) ProtoMessage()    {}
func (*BackupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{6}
}

func (m *BackupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupResponse.Unmarshal(m, b)
}
func (m *BackupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupResponse.Marshal(b, m, deterministic)
}
func (m *BackupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupResponse.Merge(m, src)
}
func (m *BackupResponse) XXX_Size() int {
	return xxx_messageInfo_BackupResponse.Size(m)
}
func (m *BackupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BackupResponse proto.InternalMessageInfo

func (m *BackupResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BackupResponse) GetBackupId() uint64 {
	if m != nil {
		return m.BackupId
	}
	return 0
}

type RestoreRequest struct {
	ClusterId            string   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	BackupId             uint64   `protobuf:"varint,2,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	RestoreType          uint32   `protobuf:"varint,3,opt,name=restore_type,json=restoreType,proto3" json:"restore_type,omitempty"`
	TargetIps            []string `protobuf:"bytes,4,rep,name=target_ips,json=targetIps,proto3" json:"target_ips,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreRequest) Reset()         { *m = RestoreRequest{} }
func (m *RestoreRequest) String() string { return proto.CompactTextString(m) }
func (*RestoreRequest) ProtoMessage()    {}
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{7}
}

func (m *RestoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreRequest.Unmarshal(m, b)
}
func (m *RestoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreRequest.Marshal(b, m, deterministic)
}
func (m *RestoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreRequest.Merge(m, src)
}
func (m *RestoreRequest) XXX_Size() int {
	return xxx_messageInfo_RestoreRequest.Size(m)
}
func (m *RestoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreRequest proto.InternalMessageInfo

func (m *RestoreRequest) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *RestoreRequest) GetBackupId() uint64 {
	if m != nil {
		return m.BackupId
	}
	return 0
}

func (m *RestoreRequest) GetRestoreType() uint32 {
	if m != nil {
		return m.RestoreType
	}
	return 0
}

func (m *RestoreRequest) GetTargetIps() []string {
	if m != nil {
		return m.TargetIps
	}
	return nil
}

type RestoreResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreResponse) Reset()         { *m = RestoreResponse{} }
func (m *RestoreResponse) String() string { return proto.CompactTextString(m) }
func (*RestoreResponse) ProtoMessage()    {}
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{8}
}

func (m *RestoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreResponse.Unmarshal(m, b)
}
func (m *RestoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreResponse.Marshal(b, m, deterministic)
}
func (m *RestoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreResponse.Merge(m, src)
}
func (m *RestoreResponse) XXX_Size() int {
	return xxx_messageInfo_RestoreResponse.Size(m)
}
func (m *RestoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreResponse proto.InternalMessageInfo

func (m *RestoreResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("rpc.BackupStatus", BackupStatus_name, BackupStatus_value)
	proto.RegisterEnum("rpc.NodeListingResponse_Entry_NodeStatus", NodeListingResponse_Entry_NodeStatus_name, NodeListingResponse_Entry_NodeStatus_value)
	proto.RegisterType((*ClusterListingResponse)(nil), "rpc.ClusterListingResponse")
	proto.RegisterType((*NodeListingRequest)(nil), "rpc.NodeListingRequest")
	proto.RegisterType((*NodeListingResponse)(nil), "rpc.NodeListingResponse")
	proto.RegisterType((*NodeListingResponse_Entry)(nil), "rpc.NodeListingResponse.Entry")
	proto.RegisterType((*BackupListingRequest)(nil), "rpc.BackupListingRequest")
	proto.RegisterType((*BackupListingResponse)(nil), "rpc.BackupListingResponse")
	proto.RegisterType((*BackupListingResponse_Entry)(nil), "rpc.BackupListingResponse.Entry")
	proto.RegisterType((*BackupRequest)(nil), "rpc.BackupRequest")
	proto.RegisterType((*BackupResponse)(nil), "rpc.BackupResponse")
	proto.RegisterType((*RestoreRequest)(nil), "rpc.RestoreRequest")
	proto.RegisterType((*RestoreResponse)(nil), "rpc.RestoreResponse")
}

func init() {
	proto.RegisterFile("src/main/proto/cassandra-backup.proto", fileDescriptor_8e42e29e62bf55da)
}

var fileDescriptor_8e42e29e62bf55da = []byte{
	// 845 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x41, 0x73, 0xdb, 0x44,
	0x14, 0x46, 0xb2, 0x13, 0x47, 0x4f, 0x8e, 0x63, 0xb6, 0xa1, 0xa8, 0x4a, 0x4a, 0x12, 0x31, 0x30,
	0x49, 0x00, 0x69, 0x48, 0x87, 0x01, 0x72, 0x73, 0x5c, 0x51, 0x0c, 0xae, 0x93, 0x51, 0xd2, 0x32,
	0x70, 0x29, 0x1b, 0x79, 0x71, 0x35, 0x89, 0xa5, 0xad, 0x76, 0x0d, 0xe3, 0xe9, 0xf4, 0xc2, 0x89,
	0x13, 0x17, 0x2e, 0xfc, 0x07, 0xee, 0xdc, 0xf9, 0x0d, 0xfc, 0x05, 0x6e, 0xfc, 0x09, 0x46, 0xbb,
	0x2b, 0xc5, 0x52, 0xec, 0x34, 0xdc, 0xb4, 0xdf, 0xdb, 0xf7, 0xbe, 0xf7, 0xbe, 0xf7, 0xf6, 0x09,
	0xde, 0x63, 0x69, 0xe8, 0x8d, 0x71, 0x14, 0x7b, 0x34, 0x4d, 0x78, 0xe2, 0x85, 0x98, 0x31, 0x1c,
	0x0f, 0x53, 0xfc, 0xd1, 0x39, 0x0e, 0x2f, 0x26, 0xd4, 0x15, 0x30, 0xaa, 0xa5, 0x34, 0xb4, 0x37,
	0x47, 0x49, 0x32, 0xba, 0x24, 0x1e, 0xa6, 0x91, 0x87, 0xe3, 0x38, 0xe1, 0x98, 0x47, 0x49, 0xcc,
	0xe4, 0x15, 0x7b, 0x43, 0x59, 0xc5, 0xe9, 0x7c, 0xf2, 0x83, 0x47, 0xc6, 0x94, 0x4f, 0xa5, 0xd1,
	0xf9, 0x14, 0xee, 0x76, 0x2f, 0x27, 0x8c, 0x93, 0xb4, 0x1f, 0x31, 0x1e, 0xc5, 0xa3, 0x80, 0x30,
	0x9a, 0xc4, 0x8c, 0xa0, 0xfb, 0x00, 0xa1, 0xb4, 0x3c, 0x8b, 0x86, 0x96, 0xb6, 0x5d, 0xdb, 0x35,
	0x02, 0x43, 0x21, 0xbd, 0xa1, 0xf3, 0x00, 0xd0, 0x20, 0x19, 0x92, 0xc2, 0xeb, 0xc5, 0x84, 0x30,
	0x7e, 0xcd, 0x49, 0x2b, 0x3b, 0xfd, 0xa2, 0xc3, 0x9d, 0x92, 0x97, 0xe2, 0xfa, 0x0c, 0x1a, 0x24,
	0xe6, 0x69, 0x44, 0x98, 0x20, 0x32, 0x0f, 0xde, 0x71, 0x53, 0x1a, 0xba, 0x73, 0xae, 0xba, 0x7e,
	0xcc, 0xd3, 0x69, 0x90, 0x5f, 0xb7, 0xff, 0xd4, 0x60, 0x49, 0x40, 0xa8, 0x05, 0x7a, 0x44, 0x15,
	0xa5, 0x1e, 0x51, 0xd4, 0x81, 0x65, 0xc6, 0x31, 0x9f, 0x30, 0x4b, 0xdf, 0xd6, 0x76, 0x5b, 0x07,
	0x7b, 0x37, 0x87, 0x14, 0x96, 0x53, 0xe1, 0x10, 0x28, 0x47, 0xe7, 0x3b, 0x80, 0x2b, 0x14, 0x99,
	0xd0, 0x78, 0x32, 0xf8, 0x7a, 0x70, 0xfc, 0xcd, 0xa0, 0xfd, 0x06, 0x5a, 0x81, 0x7a, 0xbf, 0xf7,
	0xd4, 0x6f, 0x6b, 0x19, 0xdc, 0xf7, 0x3b, 0x4f, 0x7b, 0x83, 0x47, 0x6d, 0x1d, 0x01, 0x2c, 0x3f,
	0x3e, 0x16, 0xdf, 0xb5, 0xcc, 0xf0, 0xd5, 0x71, 0x6f, 0x90, 0x1d, 0xea, 0x68, 0x0d, 0xcc, 0x27,
	0x83, 0xc0, 0xef, 0x74, 0xbf, 0xec, 0x1c, 0xf5, 0xfd, 0xf6, 0x92, 0xf3, 0x3d, 0xac, 0x1f, 0x89,
	0x46, 0xfe, 0x2f, 0x05, 0xd1, 0x06, 0x18, 0x1c, 0xa7, 0x23, 0xc2, 0x9f, 0x45, 0x54, 0x14, 0x66,
	0x04, 0x2b, 0x12, 0xe8, 0x51, 0xd4, 0x04, 0x2d, 0xb6, 0x6a, 0xdb, 0xda, 0xee, 0x6a, 0xa0, 0xc5,
	0xce, 0x5f, 0x3a, 0xbc, 0x55, 0xa1, 0x50, 0x72, 0x1f, 0x56, 0xe5, 0xde, 0x16, 0xda, 0xcc, 0xbd,
	0x5c, 0x15, 0xfc, 0xdf, 0x42, 0xf0, 0x2d, 0x30, 0x59, 0x8c, 0x29, 0x7b, 0x9e, 0xf0, 0xab, 0x54,
	0x21, 0x87, 0x64, 0xae, 0x72, 0x56, 0x33, 0x73, 0x96, 0x6b, 0x3d, 0x58, 0x91, 0x40, 0x6f, 0x58,
	0xa9, 0xb3, 0x76, 0x63, 0x9d, 0xf5, 0x4a, 0x9d, 0x5b, 0x60, 0xaa, 0xc0, 0x7c, 0x4a, 0x89, 0xb5,
	0x24, 0x2a, 0x06, 0x09, 0x9d, 0x4d, 0x29, 0x41, 0x7b, 0x45, 0xef, 0x97, 0x45, 0xef, 0xdf, 0x9c,
	0xa9, 0xaf, 0xdc, 0x63, 0xb4, 0x09, 0x06, 0x8f, 0xc6, 0x84, 0x71, 0x3c, 0xa6, 0x56, 0x43, 0x24,
	0x79, 0x05, 0x38, 0x7f, 0x68, 0xb0, 0x2a, 0xdd, 0x6e, 0xd9, 0x9f, 0x4a, 0x6a, 0xfa, 0xb5, 0xd4,
	0x4a, 0x85, 0xd5, 0x2a, 0x85, 0x6d, 0x82, 0x71, 0x41, 0xa6, 0x8c, 0xe2, 0x90, 0x30, 0xab, 0x2e,
	0x9f, 0x5c, 0x01, 0x54, 0x05, 0x5f, 0xaa, 0x0a, 0xee, 0x3c, 0x82, 0x56, 0x9e, 0xac, 0xea, 0xb4,
	0x05, 0x8d, 0x31, 0x61, 0x0c, 0x8f, 0x88, 0x4a, 0x35, 0x3f, 0xde, 0xd8, 0x1c, 0xe7, 0x57, 0x0d,
	0x5a, 0x01, 0x61, 0x3c, 0x49, 0xc9, 0xed, 0xe7, 0x72, 0x71, 0xaf, 0x77, 0xa0, 0x99, 0xca, 0x68,
	0x52, 0x15, 0x39, 0xa2, 0xa6, 0xc2, 0x84, 0x2c, 0xf7, 0x01, 0x0a, 0x59, 0x8a, 0xd2, 0x73, 0x5d,
	0x98, 0xf3, 0x01, 0xac, 0x15, 0xf9, 0xbc, 0xae, 0xb4, 0xfd, 0x2e, 0x34, 0x67, 0x5b, 0x5d, 0x7e,
	0xb8, 0x26, 0x34, 0x4e, 0xcf, 0x3a, 0xc1, 0x99, 0xff, 0xb0, 0xad, 0xa1, 0x55, 0x30, 0xba, 0xc7,
	0x8f, 0x4f, 0xfa, 0x7e, 0x76, 0x14, 0xaf, 0xf7, 0x8b, 0x4e, 0xaf, 0xef, 0x3f, 0x6c, 0xd7, 0x0e,
	0x7e, 0xaf, 0xc3, 0x5a, 0x37, 0xdf, 0xb9, 0x32, 0x1c, 0xfa, 0x16, 0x9a, 0xa7, 0xcf, 0x93, 0x9f,
	0xd4, 0xc2, 0x64, 0xe8, 0xae, 0x2b, 0x57, 0xab, 0x9b, 0xaf, 0x56, 0xd7, 0xcf, 0x56, 0xab, 0xbd,
	0x21, 0xc6, 0x6d, 0xfe, 0x5e, 0x75, 0xd6, 0x7f, 0xfe, 0xfb, 0x9f, 0xdf, 0xf4, 0x16, 0x6a, 0x7a,
	0x3f, 0x7e, 0xec, 0x85, 0x79, 0x28, 0x0c, 0x46, 0x76, 0x31, 0x5b, 0x37, 0x0c, 0xbd, 0x7d, 0x7d,
	0x55, 0x89, 0x26, 0xd8, 0xd6, 0xa2, 0x1d, 0xe6, 0xec, 0x88, 0xa8, 0x1b, 0xe8, 0xde, 0x6c, 0x54,
	0xef, 0xe5, 0x55, 0xcb, 0x5e, 0xa1, 0x04, 0xcc, 0xcc, 0x4b, 0xd6, 0xc2, 0xd0, 0xbd, 0x79, 0x6f,
	0x5e, 0xd2, 0xd8, 0x8b, 0xd7, 0x81, 0xb3, 0x27, 0x88, 0xde, 0x45, 0x3b, 0x0b, 0x89, 0xbc, 0x73,
	0xc5, 0x10, 0x02, 0x9c, 0xe1, 0x0b, 0xa2, 0xc4, 0x43, 0x33, 0x41, 0x73, 0xa2, 0x3b, 0x25, 0x4c,
	0x31, 0x7c, 0x28, 0x18, 0xde, 0x77, 0x5e, 0xcf, 0x70, 0xa8, 0xed, 0xa3, 0x17, 0xb0, 0xaa, 0x26,
	0x43, 0xf1, 0xc8, 0x98, 0xe5, 0xe9, 0xb5, 0xd7, 0xcb, 0xa0, 0x62, 0xfa, 0x44, 0x30, 0x79, 0xf6,
	0xfe, 0x62, 0xa6, 0x21, 0xe6, 0xd8, 0x7b, 0x59, 0x8c, 0xf6, 0xab, 0x43, 0x6d, 0xff, 0xe8, 0x73,
	0xd8, 0x0a, 0x93, 0xb1, 0xcb, 0x42, 0x7c, 0x89, 0x53, 0x57, 0xfd, 0x8e, 0x8b, 0xff, 0x73, 0xc6,
	0x74, 0xb4, 0x5e, 0x19, 0x9d, 0x93, 0x6c, 0x40, 0x4e, 0xb4, 0xf3, 0x65, 0x31, 0x29, 0x0f, 0xfe,
	0x0b, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x73, 0x4b, 0x2e, 0xde, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CassandraBackupClient is the client API for CassandraBackup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CassandraBackupClient interface {
	ShowClusters(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ClusterListingResponse, error)
	ListNodes(ctx context.Context, in *NodeListingRequest, opts ...grpc.CallOption) (*NodeListingResponse, error)
	ListBackups(ctx context.Context, in *BackupListingRequest, opts ...grpc.CallOption) (*BackupListingResponse, error)
	TakeBackup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error)
	RestoreBackup(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
}

type cassandraBackupClient struct {
	cc *grpc.ClientConn
}

func NewCassandraBackupClient(cc *grpc.ClientConn) CassandraBackupClient {
	return &cassandraBackupClient{cc}
}

func (c *cassandraBackupClient) ShowClusters(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ClusterListingResponse, error) {
	out := new(ClusterListingResponse)
	err := c.cc.Invoke(ctx, "/rpc.CassandraBackup/ShowClusters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cassandraBackupClient) ListNodes(ctx context.Context, in *NodeListingRequest, opts ...grpc.CallOption) (*NodeListingResponse, error) {
	out := new(NodeListingResponse)
	err := c.cc.Invoke(ctx, "/rpc.CassandraBackup/ListNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cassandraBackupClient) ListBackups(ctx context.Context, in *BackupListingRequest, opts ...grpc.CallOption) (*BackupListingResponse, error) {
	out := new(BackupListingResponse)
	err := c.cc.Invoke(ctx, "/rpc.CassandraBackup/ListBackups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cassandraBackupClient) TakeBackup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error) {
	out := new(BackupResponse)
	err := c.cc.Invoke(ctx, "/rpc.CassandraBackup/TakeBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cassandraBackupClient) RestoreBackup(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, "/rpc.CassandraBackup/RestoreBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CassandraBackupServer is the server API for CassandraBackup service.
type CassandraBackupServer interface {
	ShowClusters(context.Context, *empty.Empty) (*ClusterListingResponse, error)
	ListNodes(context.Context, *NodeListingRequest) (*NodeListingResponse, error)
	ListBackups(context.Context, *BackupListingRequest) (*BackupListingResponse, error)
	TakeBackup(context.Context, *BackupRequest) (*BackupResponse, error)
	RestoreBackup(context.Context, *RestoreRequest) (*RestoreResponse, error)
}

// UnimplementedCassandraBackupServer can be embedded to have forward compatible implementations.
type UnimplementedCassandraBackupServer struct {
}

func (*UnimplementedCassandraBackupServer) ShowClusters(ctx context.Context, req *empty.Empty) (*ClusterListingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowClusters not implemented")
}
func (*UnimplementedCassandraBackupServer) ListNodes(ctx context.Context, req *NodeListingRequest) (*NodeListingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}
func (*UnimplementedCassandraBackupServer) ListBackups(ctx context.Context, req *BackupListingRequest) (*BackupListingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBackups not implemented")
}
func (*UnimplementedCassandraBackupServer) TakeBackup(ctx context.Context, req *BackupRequest) (*BackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TakeBackup not implemented")
}
func (*UnimplementedCassandraBackupServer) RestoreBackup(ctx context.Context, req *RestoreRequest) (*RestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreBackup not implemented")
}

func RegisterCassandraBackupServer(s *grpc.Server, srv CassandraBackupServer) {
	s.RegisterService(&_CassandraBackup_serviceDesc, srv)
}

func _CassandraBackup_ShowClusters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CassandraBackupServer).ShowClusters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.CassandraBackup/ShowClusters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CassandraBackupServer).ShowClusters(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CassandraBackup_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CassandraBackupServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.CassandraBackup/ListNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CassandraBackupServer).ListNodes(ctx, req.(*NodeListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CassandraBackup_ListBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CassandraBackupServer).ListBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.CassandraBackup/ListBackups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CassandraBackupServer).ListBackups(ctx, req.(*BackupListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CassandraBackup_TakeBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CassandraBackupServer).TakeBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.CassandraBackup/TakeBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CassandraBackupServer).TakeBackup(ctx, req.(*BackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CassandraBackup_RestoreBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CassandraBackupServer).RestoreBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.CassandraBackup/RestoreBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CassandraBackupServer).RestoreBackup(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CassandraBackup_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.CassandraBackup",
	HandlerType: (*CassandraBackupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowClusters",
			Handler:    _CassandraBackup_ShowClusters_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _CassandraBackup_ListNodes_Handler,
		},
		{
			MethodName: "ListBackups",
			Handler:    _CassandraBackup_ListBackups_Handler,
		},
		{
			MethodName: "TakeBackup",
			Handler:    _CassandraBackup_TakeBackup_Handler,
		},
		{
			MethodName: "RestoreBackup",
			Handler:    _CassandraBackup_RestoreBackup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/main/proto/cassandra-backup.proto",
}
