// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/main/proto/cassandra-backup.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OperationStatus int32

const (
	OperationStatus_UNKNOWN     OperationStatus = 0
	OperationStatus_INITIALIZED OperationStatus = 1
	OperationStatus_STARTED     OperationStatus = 2
	OperationStatus_COMPLETED   OperationStatus = 3
	OperationStatus_FAILED      OperationStatus = 4
)

var OperationStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "INITIALIZED",
	2: "STARTED",
	3: "COMPLETED",
	4: "FAILED",
}

var OperationStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"INITIALIZED": 1,
	"STARTED":     2,
	"COMPLETED":   3,
	"FAILED":      4,
}

func (x OperationStatus) String() string {
	return proto.EnumName(OperationStatus_name, int32(x))
}

func (OperationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{0}
}

type ClusterRegistrationRequest struct {
	CassandraHost        string   `protobuf:"bytes,1,opt,name=cassandra_host,json=cassandraHost,proto3" json:"cassandra_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterRegistrationRequest) Reset()         { *m = ClusterRegistrationRequest{} }
func (m *ClusterRegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*ClusterRegistrationRequest) ProtoMessage()    {}
func (*ClusterRegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{0}
}

func (m *ClusterRegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterRegistrationRequest.Unmarshal(m, b)
}
func (m *ClusterRegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterRegistrationRequest.Marshal(b, m, deterministic)
}
func (m *ClusterRegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterRegistrationRequest.Merge(m, src)
}
func (m *ClusterRegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_ClusterRegistrationRequest.Size(m)
}
func (m *ClusterRegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterRegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterRegistrationRequest proto.InternalMessageInfo

func (m *ClusterRegistrationRequest) GetCassandraHost() string {
	if m != nil {
		return m.CassandraHost
	}
	return ""
}

type ClusterRegistrationResponse struct {
	ClusterId            string   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	TargetIps            []string `protobuf:"bytes,2,rep,name=target_ips,json=targetIps,proto3" json:"target_ips,omitempty"`
	Keyspaces            []string `protobuf:"bytes,3,rep,name=keyspaces,proto3" json:"keyspaces,omitempty"`
	DataDir              string   `protobuf:"bytes,4,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterRegistrationResponse) Reset()         { *m = ClusterRegistrationResponse{} }
func (m *ClusterRegistrationResponse) String() string { return proto.CompactTextString(m) }
func (*ClusterRegistrationResponse) ProtoMessage()    {}
func (*ClusterRegistrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{1}
}

func (m *ClusterRegistrationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterRegistrationResponse.Unmarshal(m, b)
}
func (m *ClusterRegistrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterRegistrationResponse.Marshal(b, m, deterministic)
}
func (m *ClusterRegistrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterRegistrationResponse.Merge(m, src)
}
func (m *ClusterRegistrationResponse) XXX_Size() int {
	return xxx_messageInfo_ClusterRegistrationResponse.Size(m)
}
func (m *ClusterRegistrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterRegistrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterRegistrationResponse proto.InternalMessageInfo

func (m *ClusterRegistrationResponse) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *ClusterRegistrationResponse) GetTargetIps() []string {
	if m != nil {
		return m.TargetIps
	}
	return nil
}

func (m *ClusterRegistrationResponse) GetKeyspaces() []string {
	if m != nil {
		return m.Keyspaces
	}
	return nil
}

func (m *ClusterRegistrationResponse) GetDataDir() string {
	if m != nil {
		return m.DataDir
	}
	return ""
}

type ClusterListingRequest struct {
	ClusterId            string   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterListingRequest) Reset()         { *m = ClusterListingRequest{} }
func (m *ClusterListingRequest) String() string { return proto.CompactTextString(m) }
func (*ClusterListingRequest) ProtoMessage()    {}
func (*ClusterListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{2}
}

func (m *ClusterListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterListingRequest.Unmarshal(m, b)
}
func (m *ClusterListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterListingRequest.Marshal(b, m, deterministic)
}
func (m *ClusterListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterListingRequest.Merge(m, src)
}
func (m *ClusterListingRequest) XXX_Size() int {
	return xxx_messageInfo_ClusterListingRequest.Size(m)
}
func (m *ClusterListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterListingRequest proto.InternalMessageInfo

func (m *ClusterListingRequest) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *ClusterListingRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ClusterListingResponse struct {
	Entries              []*ClusterListingResponse_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ClusterListingResponse) Reset()         { *m = ClusterListingResponse{} }
func (m *ClusterListingResponse) String() string { return proto.CompactTextString(m) }
func (*ClusterListingResponse) ProtoMessage()    {}
func (*ClusterListingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{3}
}

func (m *ClusterListingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterListingResponse.Unmarshal(m, b)
}
func (m *ClusterListingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterListingResponse.Marshal(b, m, deterministic)
}
func (m *ClusterListingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterListingResponse.Merge(m, src)
}
func (m *ClusterListingResponse) XXX_Size() int {
	return xxx_messageInfo_ClusterListingResponse.Size(m)
}
func (m *ClusterListingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterListingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterListingResponse proto.InternalMessageInfo

func (m *ClusterListingResponse) GetEntries() []*ClusterListingResponse_Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type ClusterListingResponse_Entry struct {
	ClusterId            string   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	TargetIps            []string `protobuf:"bytes,2,rep,name=target_ips,json=targetIps,proto3" json:"target_ips,omitempty"`
	Keyspaces            []string `protobuf:"bytes,3,rep,name=keyspaces,proto3" json:"keyspaces,omitempty"`
	DataDir              string   `protobuf:"bytes,4,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	CreatedAt            uint64   `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            uint64   `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterListingResponse_Entry) Reset()         { *m = ClusterListingResponse_Entry{} }
func (m *ClusterListingResponse_Entry) String() string { return proto.CompactTextString(m) }
func (*ClusterListingResponse_Entry) ProtoMessage()    {}
func (*ClusterListingResponse_Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{3, 0}
}

func (m *ClusterListingResponse_Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterListingResponse_Entry.Unmarshal(m, b)
}
func (m *ClusterListingResponse_Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterListingResponse_Entry.Marshal(b, m, deterministic)
}
func (m *ClusterListingResponse_Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterListingResponse_Entry.Merge(m, src)
}
func (m *ClusterListingResponse_Entry) XXX_Size() int {
	return xxx_messageInfo_ClusterListingResponse_Entry.Size(m)
}
func (m *ClusterListingResponse_Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterListingResponse_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterListingResponse_Entry proto.InternalMessageInfo

func (m *ClusterListingResponse_Entry) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *ClusterListingResponse_Entry) GetTargetIps() []string {
	if m != nil {
		return m.TargetIps
	}
	return nil
}

func (m *ClusterListingResponse_Entry) GetKeyspaces() []string {
	if m != nil {
		return m.Keyspaces
	}
	return nil
}

func (m *ClusterListingResponse_Entry) GetDataDir() string {
	if m != nil {
		return m.DataDir
	}
	return ""
}

func (m *ClusterListingResponse_Entry) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ClusterListingResponse_Entry) GetUpdatedAt() uint64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type BackupListingRequest struct {
	ClusterId            string   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	TargetIp             string   `protobuf:"bytes,2,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	SnapshotId           string   `protobuf:"bytes,4,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupListingRequest) Reset()         { *m = BackupListingRequest{} }
func (m *BackupListingRequest) String() string { return proto.CompactTextString(m) }
func (*BackupListingRequest) ProtoMessage()    {}
func (*BackupListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{4}
}

func (m *BackupListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupListingRequest.Unmarshal(m, b)
}
func (m *BackupListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupListingRequest.Marshal(b, m, deterministic)
}
func (m *BackupListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupListingRequest.Merge(m, src)
}
func (m *BackupListingRequest) XXX_Size() int {
	return xxx_messageInfo_BackupListingRequest.Size(m)
}
func (m *BackupListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackupListingRequest proto.InternalMessageInfo

func (m *BackupListingRequest) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *BackupListingRequest) GetTargetIp() string {
	if m != nil {
		return m.TargetIp
	}
	return ""
}

func (m *BackupListingRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *BackupListingRequest) GetSnapshotId() string {
	if m != nil {
		return m.SnapshotId
	}
	return ""
}

type BackupListingResponse struct {
	Entries              []*BackupListingResponse_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *BackupListingResponse) Reset()         { *m = BackupListingResponse{} }
func (m *BackupListingResponse) String() string { return proto.CompactTextString(m) }
func (*BackupListingResponse) ProtoMessage()    {}
func (*BackupListingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{5}
}

func (m *BackupListingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupListingResponse.Unmarshal(m, b)
}
func (m *BackupListingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupListingResponse.Marshal(b, m, deterministic)
}
func (m *BackupListingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupListingResponse.Merge(m, src)
}
func (m *BackupListingResponse) XXX_Size() int {
	return xxx_messageInfo_BackupListingResponse.Size(m)
}
func (m *BackupListingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupListingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BackupListingResponse proto.InternalMessageInfo

func (m *BackupListingResponse) GetEntries() []*BackupListingResponse_Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type BackupListingResponse_Entry struct {
	ClusterId            string          `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	TargetIp             string          `protobuf:"bytes,2,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	SnapshotId           string          `protobuf:"bytes,3,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	CreatedAt            uint64          `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            uint64          `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	BackupType           uint32          `protobuf:"varint,6,opt,name=backup_type,json=backupType,proto3" json:"backup_type,omitempty"`
	Status               OperationStatus `protobuf:"varint,7,opt,name=status,proto3,enum=rpc.OperationStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BackupListingResponse_Entry) Reset()         { *m = BackupListingResponse_Entry{} }
func (m *BackupListingResponse_Entry) String() string { return proto.CompactTextString(m) }
func (*BackupListingResponse_Entry) ProtoMessage()    {}
func (*BackupListingResponse_Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{5, 0}
}

func (m *BackupListingResponse_Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupListingResponse_Entry.Unmarshal(m, b)
}
func (m *BackupListingResponse_Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupListingResponse_Entry.Marshal(b, m, deterministic)
}
func (m *BackupListingResponse_Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupListingResponse_Entry.Merge(m, src)
}
func (m *BackupListingResponse_Entry) XXX_Size() int {
	return xxx_messageInfo_BackupListingResponse_Entry.Size(m)
}
func (m *BackupListingResponse_Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupListingResponse_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_BackupListingResponse_Entry proto.InternalMessageInfo

func (m *BackupListingResponse_Entry) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *BackupListingResponse_Entry) GetTargetIp() string {
	if m != nil {
		return m.TargetIp
	}
	return ""
}

func (m *BackupListingResponse_Entry) GetSnapshotId() string {
	if m != nil {
		return m.SnapshotId
	}
	return ""
}

func (m *BackupListingResponse_Entry) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *BackupListingResponse_Entry) GetUpdatedAt() uint64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *BackupListingResponse_Entry) GetBackupType() uint32 {
	if m != nil {
		return m.BackupType
	}
	return 0
}

func (m *BackupListingResponse_Entry) GetStatus() OperationStatus {
	if m != nil {
		return m.Status
	}
	return OperationStatus_UNKNOWN
}

type BackupRequest struct {
	ClusterId            string   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	TargetIps            []string `protobuf:"bytes,2,rep,name=target_ips,json=targetIps,proto3" json:"target_ips,omitempty"`
	SnapshotId           string   `protobuf:"bytes,3,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	BackupType           uint32   `protobuf:"varint,4,opt,name=backup_type,json=backupType,proto3" json:"backup_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupRequest) Reset()         { *m = BackupRequest{} }
func (m *BackupRequest) String() string { return proto.CompactTextString(m) }
func (*BackupRequest) ProtoMessage()    {}
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{6}
}

func (m *BackupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupRequest.Unmarshal(m, b)
}
func (m *BackupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupRequest.Marshal(b, m, deterministic)
}
func (m *BackupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupRequest.Merge(m, src)
}
func (m *BackupRequest) XXX_Size() int {
	return xxx_messageInfo_BackupRequest.Size(m)
}
func (m *BackupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackupRequest proto.InternalMessageInfo

func (m *BackupRequest) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *BackupRequest) GetTargetIps() []string {
	if m != nil {
		return m.TargetIps
	}
	return nil
}

func (m *BackupRequest) GetSnapshotId() string {
	if m != nil {
		return m.SnapshotId
	}
	return ""
}

func (m *BackupRequest) GetBackupType() uint32 {
	if m != nil {
		return m.BackupType
	}
	return 0
}

type BackupResponse struct {
	Status               OperationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=rpc.OperationStatus" json:"status,omitempty"`
	ClusterId            string          `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	TargetIps            []string        `protobuf:"bytes,3,rep,name=target_ips,json=targetIps,proto3" json:"target_ips,omitempty"`
	SnapshotId           string          `protobuf:"bytes,4,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	CreatedAt            uint64          `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	BackupType           uint32          `protobuf:"varint,6,opt,name=backup_type,json=backupType,proto3" json:"backup_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BackupResponse) Reset()         { *m = BackupResponse{} }
func (m *BackupResponse) String() string { return proto.CompactTextString(m) }
func (*BackupResponse) ProtoMessage()    {}
func (*BackupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{7}
}

func (m *BackupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupResponse.Unmarshal(m, b)
}
func (m *BackupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupResponse.Marshal(b, m, deterministic)
}
func (m *BackupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupResponse.Merge(m, src)
}
func (m *BackupResponse) XXX_Size() int {
	return xxx_messageInfo_BackupResponse.Size(m)
}
func (m *BackupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BackupResponse proto.InternalMessageInfo

func (m *BackupResponse) GetStatus() OperationStatus {
	if m != nil {
		return m.Status
	}
	return OperationStatus_UNKNOWN
}

func (m *BackupResponse) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *BackupResponse) GetTargetIps() []string {
	if m != nil {
		return m.TargetIps
	}
	return nil
}

func (m *BackupResponse) GetSnapshotId() string {
	if m != nil {
		return m.SnapshotId
	}
	return ""
}

func (m *BackupResponse) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *BackupResponse) GetBackupType() uint32 {
	if m != nil {
		return m.BackupType
	}
	return 0
}

type RestoreRequest struct {
	ClusterId            string   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	TargetIps            []string `protobuf:"bytes,2,rep,name=target_ips,json=targetIps,proto3" json:"target_ips,omitempty"`
	SnapshotId           string   `protobuf:"bytes,3,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	RestoreType          uint32   `protobuf:"varint,4,opt,name=restore_type,json=restoreType,proto3" json:"restore_type,omitempty"`
	SnapshotOnly         bool     `protobuf:"varint,5,opt,name=snapshot_only,json=snapshotOnly,proto3" json:"snapshot_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreRequest) Reset()         { *m = RestoreRequest{} }
func (m *RestoreRequest) String() string { return proto.CompactTextString(m) }
func (*RestoreRequest) ProtoMessage()    {}
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{8}
}

func (m *RestoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreRequest.Unmarshal(m, b)
}
func (m *RestoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreRequest.Marshal(b, m, deterministic)
}
func (m *RestoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreRequest.Merge(m, src)
}
func (m *RestoreRequest) XXX_Size() int {
	return xxx_messageInfo_RestoreRequest.Size(m)
}
func (m *RestoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreRequest proto.InternalMessageInfo

func (m *RestoreRequest) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *RestoreRequest) GetTargetIps() []string {
	if m != nil {
		return m.TargetIps
	}
	return nil
}

func (m *RestoreRequest) GetSnapshotId() string {
	if m != nil {
		return m.SnapshotId
	}
	return ""
}

func (m *RestoreRequest) GetRestoreType() uint32 {
	if m != nil {
		return m.RestoreType
	}
	return 0
}

func (m *RestoreRequest) GetSnapshotOnly() bool {
	if m != nil {
		return m.SnapshotOnly
	}
	return false
}

type RestoreResponse struct {
	Status               OperationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=rpc.OperationStatus" json:"status,omitempty"`
	ClusterId            string          `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	TargetIps            []string        `protobuf:"bytes,3,rep,name=target_ips,json=targetIps,proto3" json:"target_ips,omitempty"`
	SnapshotId           string          `protobuf:"bytes,4,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	RestoreType          uint32          `protobuf:"varint,5,opt,name=restore_type,json=restoreType,proto3" json:"restore_type,omitempty"`
	SnapshotOnly         bool            `protobuf:"varint,6,opt,name=snapshot_only,json=snapshotOnly,proto3" json:"snapshot_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RestoreResponse) Reset()         { *m = RestoreResponse{} }
func (m *RestoreResponse) String() string { return proto.CompactTextString(m) }
func (*RestoreResponse) ProtoMessage()    {}
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{9}
}

func (m *RestoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreResponse.Unmarshal(m, b)
}
func (m *RestoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreResponse.Marshal(b, m, deterministic)
}
func (m *RestoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreResponse.Merge(m, src)
}
func (m *RestoreResponse) XXX_Size() int {
	return xxx_messageInfo_RestoreResponse.Size(m)
}
func (m *RestoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreResponse proto.InternalMessageInfo

func (m *RestoreResponse) GetStatus() OperationStatus {
	if m != nil {
		return m.Status
	}
	return OperationStatus_UNKNOWN
}

func (m *RestoreResponse) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *RestoreResponse) GetTargetIps() []string {
	if m != nil {
		return m.TargetIps
	}
	return nil
}

func (m *RestoreResponse) GetSnapshotId() string {
	if m != nil {
		return m.SnapshotId
	}
	return ""
}

func (m *RestoreResponse) GetRestoreType() uint32 {
	if m != nil {
		return m.RestoreType
	}
	return 0
}

func (m *RestoreResponse) GetSnapshotOnly() bool {
	if m != nil {
		return m.SnapshotOnly
	}
	return false
}

type RestoreStatusListingRequest struct {
	ClusterId            string   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	TargetIp             string   `protobuf:"bytes,2,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	SnapshotId           string   `protobuf:"bytes,3,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Limit                int32    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreStatusListingRequest) Reset()         { *m = RestoreStatusListingRequest{} }
func (m *RestoreStatusListingRequest) String() string { return proto.CompactTextString(m) }
func (*RestoreStatusListingRequest) ProtoMessage()    {}
func (*RestoreStatusListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{10}
}

func (m *RestoreStatusListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreStatusListingRequest.Unmarshal(m, b)
}
func (m *RestoreStatusListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreStatusListingRequest.Marshal(b, m, deterministic)
}
func (m *RestoreStatusListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreStatusListingRequest.Merge(m, src)
}
func (m *RestoreStatusListingRequest) XXX_Size() int {
	return xxx_messageInfo_RestoreStatusListingRequest.Size(m)
}
func (m *RestoreStatusListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreStatusListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreStatusListingRequest proto.InternalMessageInfo

func (m *RestoreStatusListingRequest) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *RestoreStatusListingRequest) GetTargetIp() string {
	if m != nil {
		return m.TargetIp
	}
	return ""
}

func (m *RestoreStatusListingRequest) GetSnapshotId() string {
	if m != nil {
		return m.SnapshotId
	}
	return ""
}

func (m *RestoreStatusListingRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type RestoreStatusListingResponse struct {
	ClusterId            string                                `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Entries              []*RestoreStatusListingResponse_Entry `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *RestoreStatusListingResponse) Reset()         { *m = RestoreStatusListingResponse{} }
func (m *RestoreStatusListingResponse) String() string { return proto.CompactTextString(m) }
func (*RestoreStatusListingResponse) ProtoMessage()    {}
func (*RestoreStatusListingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{11}
}

func (m *RestoreStatusListingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreStatusListingResponse.Unmarshal(m, b)
}
func (m *RestoreStatusListingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreStatusListingResponse.Marshal(b, m, deterministic)
}
func (m *RestoreStatusListingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreStatusListingResponse.Merge(m, src)
}
func (m *RestoreStatusListingResponse) XXX_Size() int {
	return xxx_messageInfo_RestoreStatusListingResponse.Size(m)
}
func (m *RestoreStatusListingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreStatusListingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreStatusListingResponse proto.InternalMessageInfo

func (m *RestoreStatusListingResponse) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *RestoreStatusListingResponse) GetEntries() []*RestoreStatusListingResponse_Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type RestoreStatusListingResponse_Entry struct {
	TargetIp             string          `protobuf:"bytes,1,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	SnapshotId           string          `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	CreatedAt            uint64          `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            uint64          `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	RestoreType          uint32          `protobuf:"varint,5,opt,name=restore_type,json=restoreType,proto3" json:"restore_type,omitempty"`
	Status               OperationStatus `protobuf:"varint,6,opt,name=status,proto3,enum=rpc.OperationStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RestoreStatusListingResponse_Entry) Reset()         { *m = RestoreStatusListingResponse_Entry{} }
func (m *RestoreStatusListingResponse_Entry) String() string { return proto.CompactTextString(m) }
func (*RestoreStatusListingResponse_Entry) ProtoMessage()    {}
func (*RestoreStatusListingResponse_Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{11, 0}
}

func (m *RestoreStatusListingResponse_Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreStatusListingResponse_Entry.Unmarshal(m, b)
}
func (m *RestoreStatusListingResponse_Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreStatusListingResponse_Entry.Marshal(b, m, deterministic)
}
func (m *RestoreStatusListingResponse_Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreStatusListingResponse_Entry.Merge(m, src)
}
func (m *RestoreStatusListingResponse_Entry) XXX_Size() int {
	return xxx_messageInfo_RestoreStatusListingResponse_Entry.Size(m)
}
func (m *RestoreStatusListingResponse_Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreStatusListingResponse_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreStatusListingResponse_Entry proto.InternalMessageInfo

func (m *RestoreStatusListingResponse_Entry) GetTargetIp() string {
	if m != nil {
		return m.TargetIp
	}
	return ""
}

func (m *RestoreStatusListingResponse_Entry) GetSnapshotId() string {
	if m != nil {
		return m.SnapshotId
	}
	return ""
}

func (m *RestoreStatusListingResponse_Entry) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *RestoreStatusListingResponse_Entry) GetUpdatedAt() uint64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *RestoreStatusListingResponse_Entry) GetRestoreType() uint32 {
	if m != nil {
		return m.RestoreType
	}
	return 0
}

func (m *RestoreStatusListingResponse_Entry) GetStatus() OperationStatus {
	if m != nil {
		return m.Status
	}
	return OperationStatus_UNKNOWN
}

type PauseRequest struct {
	WaitOutstanding      bool     `protobuf:"varint,1,opt,name=wait_outstanding,json=waitOutstanding,proto3" json:"wait_outstanding,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PauseRequest) Reset()         { *m = PauseRequest{} }
func (m *PauseRequest) String() string { return proto.CompactTextString(m) }
func (*PauseRequest) ProtoMessage()    {}
func (*PauseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{12}
}

func (m *PauseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PauseRequest.Unmarshal(m, b)
}
func (m *PauseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PauseRequest.Marshal(b, m, deterministic)
}
func (m *PauseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PauseRequest.Merge(m, src)
}
func (m *PauseRequest) XXX_Size() int {
	return xxx_messageInfo_PauseRequest.Size(m)
}
func (m *PauseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PauseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PauseRequest proto.InternalMessageInfo

func (m *PauseRequest) GetWaitOutstanding() bool {
	if m != nil {
		return m.WaitOutstanding
	}
	return false
}

type StatsResponse struct {
	Stats                string   `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatsResponse) Reset()         { *m = StatsResponse{} }
func (m *StatsResponse) String() string { return proto.CompactTextString(m) }
func (*StatsResponse) ProtoMessage()    {}
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e42e29e62bf55da, []int{13}
}

func (m *StatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsResponse.Unmarshal(m, b)
}
func (m *StatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsResponse.Marshal(b, m, deterministic)
}
func (m *StatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsResponse.Merge(m, src)
}
func (m *StatsResponse) XXX_Size() int {
	return xxx_messageInfo_StatsResponse.Size(m)
}
func (m *StatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatsResponse proto.InternalMessageInfo

func (m *StatsResponse) GetStats() string {
	if m != nil {
		return m.Stats
	}
	return ""
}

func init() {
	proto.RegisterEnum("rpc.OperationStatus", OperationStatus_name, OperationStatus_value)
	proto.RegisterType((*ClusterRegistrationRequest)(nil), "rpc.ClusterRegistrationRequest")
	proto.RegisterType((*ClusterRegistrationResponse)(nil), "rpc.ClusterRegistrationResponse")
	proto.RegisterType((*ClusterListingRequest)(nil), "rpc.ClusterListingRequest")
	proto.RegisterType((*ClusterListingResponse)(nil), "rpc.ClusterListingResponse")
	proto.RegisterType((*ClusterListingResponse_Entry)(nil), "rpc.ClusterListingResponse.Entry")
	proto.RegisterType((*BackupListingRequest)(nil), "rpc.BackupListingRequest")
	proto.RegisterType((*BackupListingResponse)(nil), "rpc.BackupListingResponse")
	proto.RegisterType((*BackupListingResponse_Entry)(nil), "rpc.BackupListingResponse.Entry")
	proto.RegisterType((*BackupRequest)(nil), "rpc.BackupRequest")
	proto.RegisterType((*BackupResponse)(nil), "rpc.BackupResponse")
	proto.RegisterType((*RestoreRequest)(nil), "rpc.RestoreRequest")
	proto.RegisterType((*RestoreResponse)(nil), "rpc.RestoreResponse")
	proto.RegisterType((*RestoreStatusListingRequest)(nil), "rpc.RestoreStatusListingRequest")
	proto.RegisterType((*RestoreStatusListingResponse)(nil), "rpc.RestoreStatusListingResponse")
	proto.RegisterType((*RestoreStatusListingResponse_Entry)(nil), "rpc.RestoreStatusListingResponse.Entry")
	proto.RegisterType((*PauseRequest)(nil), "rpc.PauseRequest")
	proto.RegisterType((*StatsResponse)(nil), "rpc.StatsResponse")
}

func init() {
	proto.RegisterFile("src/main/proto/cassandra-backup.proto", fileDescriptor_8e42e29e62bf55da)
}

var fileDescriptor_8e42e29e62bf55da = []byte{
	// 1099 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xce, 0xd8, 0x5e, 0x27, 0x7e, 0x8e, 0x93, 0x74, 0xe2, 0x16, 0xc7, 0x0e, 0x8a, 0xb3, 0x55,
	0x20, 0xad, 0x82, 0x57, 0x0d, 0x45, 0xa8, 0xe5, 0xe4, 0x24, 0x46, 0x58, 0x84, 0x24, 0xda, 0xa6,
	0xaa, 0xc4, 0xc5, 0x9a, 0xd8, 0x83, 0xbb, 0xc4, 0xde, 0x5d, 0x76, 0xc6, 0x20, 0xab, 0xea, 0x85,
	0x1b, 0x27, 0x2a, 0xd1, 0x7f, 0x84, 0x13, 0x17, 0xee, 0x48, 0x5c, 0x41, 0xe2, 0xc4, 0x0d, 0x71,
	0xe7, 0x3f, 0x40, 0xf3, 0x63, 0xd7, 0xf6, 0x62, 0x7b, 0x5d, 0x09, 0x41, 0x8f, 0xfb, 0xde, 0xcc,
	0xfb, 0xde, 0xf7, 0xbe, 0x79, 0x6f, 0x67, 0x60, 0x8f, 0x05, 0x6d, 0xab, 0x4f, 0x1c, 0xd7, 0xf2,
	0x03, 0x8f, 0x7b, 0x56, 0x9b, 0x30, 0x46, 0xdc, 0x4e, 0x40, 0xde, 0xb9, 0x22, 0xed, 0xeb, 0x81,
	0x5f, 0x93, 0x66, 0x9c, 0x0e, 0xfc, 0x76, 0x79, 0xbb, 0xeb, 0x79, 0xdd, 0x1e, 0xb5, 0x88, 0xef,
	0x58, 0xc4, 0x75, 0x3d, 0x4e, 0xb8, 0xe3, 0xb9, 0x4c, 0x2d, 0x29, 0x57, 0xb4, 0x57, 0x7e, 0x5d,
	0x0d, 0x3e, 0xb3, 0x68, 0xdf, 0xe7, 0x43, 0xe5, 0x34, 0x8f, 0xa1, 0x7c, 0xdc, 0x1b, 0x30, 0x4e,
	0x03, 0x9b, 0x76, 0x1d, 0xc6, 0x03, 0xb9, 0xd5, 0xa6, 0x5f, 0x0c, 0x28, 0xe3, 0x78, 0x0f, 0xd6,
	0x22, 0xdc, 0xd6, 0x53, 0x8f, 0xf1, 0x12, 0xaa, 0xa2, 0xfd, 0x9c, 0x5d, 0x88, 0xac, 0x1f, 0x79,
	0x8c, 0x9b, 0x2f, 0x11, 0x54, 0xa6, 0x46, 0x61, 0xbe, 0xe7, 0x32, 0x8a, 0xdf, 0x04, 0x68, 0x2b,
	0x77, 0xcb, 0xe9, 0xe8, 0x10, 0x39, 0x6d, 0x69, 0x76, 0x84, 0x9b, 0x93, 0xa0, 0x4b, 0x79, 0xcb,
	0xf1, 0x59, 0x29, 0x55, 0x4d, 0x0b, 0xb7, 0xb2, 0x34, 0x7d, 0x86, 0xb7, 0x21, 0x77, 0x4d, 0x87,
	0xcc, 0x27, 0x6d, 0xca, 0x4a, 0x69, 0xe5, 0x8d, 0x0c, 0x78, 0x0b, 0x56, 0x3a, 0x84, 0x93, 0x56,
	0xc7, 0x09, 0x4a, 0x19, 0x19, 0x79, 0x59, 0x7c, 0x9f, 0x38, 0x81, 0x79, 0x0a, 0x37, 0x75, 0x56,
	0xa7, 0x0e, 0xe3, 0x8e, 0xdb, 0x0d, 0x69, 0x25, 0xe4, 0x53, 0x04, 0xa3, 0xe7, 0xf4, 0x1d, 0x5e,
	0x4a, 0x55, 0xd1, 0xbe, 0x61, 0xab, 0x0f, 0xf3, 0x65, 0x0a, 0x6e, 0xc5, 0xc3, 0x69, 0x7e, 0x1f,
	0xc0, 0x32, 0x75, 0x79, 0xe0, 0x50, 0x56, 0x42, 0xd5, 0xf4, 0x7e, 0xfe, 0x70, 0xb7, 0x16, 0xf8,
	0xed, 0xda, 0xf4, 0xd5, 0xb5, 0x86, 0xcb, 0x83, 0xa1, 0x1d, 0xee, 0x28, 0xff, 0x88, 0xc0, 0x90,
	0xa6, 0xff, 0xa9, 0x4c, 0x12, 0x36, 0xa0, 0x84, 0xd3, 0x4e, 0x8b, 0xf0, 0x92, 0x51, 0x45, 0xfb,
	0x19, 0x3b, 0xa7, 0x2d, 0x75, 0x59, 0xac, 0x81, 0xdf, 0x09, 0xdd, 0x59, 0xe5, 0xd6, 0x96, 0x3a,
	0x37, 0xbf, 0x41, 0x50, 0x3c, 0x92, 0x27, 0xf2, 0xd5, 0x8a, 0x5c, 0x81, 0x5c, 0xc4, 0x46, 0x16,
	0x3a, 0x67, 0xaf, 0x84, 0x64, 0x46, 0x0a, 0xa4, 0xc7, 0x14, 0xc0, 0x3b, 0x90, 0x67, 0x2e, 0xf1,
	0xd9, 0x53, 0x8f, 0x8b, 0x90, 0x8a, 0x06, 0x84, 0xa6, 0x66, 0xc7, 0xfc, 0x29, 0x05, 0x37, 0x63,
	0xb9, 0x68, 0x85, 0x1e, 0xc6, 0x15, 0xaa, 0x4a, 0x85, 0xa6, 0x2e, 0x8e, 0x0b, 0xf4, 0xd7, 0xa2,
	0x02, 0xcd, 0xa5, 0x14, 0x4b, 0x3e, 0x1d, 0x4f, 0x3e, 0x26, 0x43, 0x66, 0xbe, 0x0c, 0x46, 0x4c,
	0x06, 0x11, 0x5e, 0xcd, 0x85, 0x16, 0x1f, 0xfa, 0x54, 0xca, 0x54, 0xb0, 0x41, 0x99, 0x2e, 0x87,
	0x3e, 0xc5, 0x07, 0x90, 0x65, 0x9c, 0xf0, 0x01, 0x2b, 0x2d, 0x57, 0xd1, 0xfe, 0xda, 0x61, 0x51,
	0x16, 0xe0, 0xdc, 0xa7, 0xaa, 0x57, 0x1f, 0x49, 0x9f, 0xad, 0xd7, 0x98, 0xdf, 0x22, 0x28, 0xa8,
	0xe2, 0x2c, 0x28, 0x67, 0xc2, 0xe1, 0x4c, 0x64, 0x1f, 0xcb, 0x3f, 0x13, 0xcf, 0xdf, 0xfc, 0x1d,
	0xc1, 0x5a, 0x98, 0x91, 0x16, 0x75, 0x44, 0x09, 0x25, 0x53, 0x8a, 0x11, 0x48, 0xcd, 0x27, 0x90,
	0x4e, 0x20, 0x90, 0x49, 0x90, 0xef, 0x1f, 0x5d, 0x94, 0xa4, 0x8f, 0xf9, 0x03, 0x82, 0x35, 0x9b,
	0x32, 0xee, 0x05, 0xf4, 0x3f, 0x2a, 0xf9, 0x2e, 0xac, 0x06, 0x0a, 0x70, 0xbc, 0xe6, 0x79, 0x6d,
	0x93, 0x87, 0xe6, 0x36, 0x14, 0xa2, 0x18, 0x9e, 0xdb, 0x1b, 0x4a, 0x5e, 0x2b, 0xf6, 0x6a, 0x68,
	0x3c, 0x77, 0x7b, 0x43, 0xf3, 0x4f, 0x04, 0xeb, 0x51, 0xe6, 0xaf, 0xa3, 0x34, 0x71, 0xa2, 0xc6,
	0x02, 0x44, 0xb3, 0x53, 0x88, 0xbe, 0x40, 0x50, 0xd1, 0x44, 0x15, 0x81, 0x7f, 0x71, 0xe2, 0x25,
	0xaa, 0x15, 0x8d, 0xc4, 0xcc, 0xf8, 0x4f, 0xe9, 0xb7, 0x14, 0x6c, 0x4f, 0x4f, 0x69, 0xb1, 0x5f,
	0x6f, 0x7d, 0x34, 0x17, 0xd3, 0x72, 0x2e, 0xbe, 0x2d, 0x85, 0x9a, 0x17, 0x32, 0x3e, 0x1e, 0x7f,
	0x8d, 0xc6, 0xe3, 0x04, 0x41, 0x34, 0x9f, 0x60, 0x2a, 0xa1, 0x81, 0xd2, 0xf3, 0xe7, 0x5f, 0x26,
	0x3e, 0xff, 0x16, 0xd0, 0x78, 0x74, 0x26, 0xb3, 0x0b, 0x4c, 0xc0, 0x07, 0xb0, 0x7a, 0x41, 0x06,
	0x2c, 0x6a, 0xc6, 0x3b, 0xb0, 0xf1, 0x15, 0x71, 0x78, 0xcb, 0x1b, 0x70, 0xc6, 0x89, 0xdb, 0x71,
	0xdc, 0xae, 0xe4, 0xb8, 0x62, 0xaf, 0x0b, 0xfb, 0xf9, 0xc8, 0x6c, 0xee, 0x41, 0x41, 0x04, 0x63,
	0x91, 0x08, 0x45, 0x30, 0x44, 0x54, 0xa6, 0x8b, 0xa2, 0x3e, 0xee, 0x3e, 0x81, 0xf5, 0x18, 0x38,
	0xce, 0xc3, 0xf2, 0xe3, 0xb3, 0x8f, 0xcf, 0xce, 0x9f, 0x9c, 0x6d, 0x2c, 0xe1, 0x75, 0xc8, 0x37,
	0xcf, 0x9a, 0x97, 0xcd, 0xfa, 0x69, 0xf3, 0xd3, 0xc6, 0xc9, 0x06, 0x12, 0xde, 0x47, 0x97, 0x75,
	0xfb, 0xb2, 0x71, 0xb2, 0x91, 0xc2, 0x05, 0xc8, 0x1d, 0x9f, 0x7f, 0x72, 0x71, 0xda, 0x10, 0x9f,
	0x69, 0x0c, 0x90, 0xfd, 0xb0, 0xde, 0x3c, 0x6d, 0x9c, 0x6c, 0x64, 0x0e, 0x7f, 0x36, 0x60, 0xfd,
	0x38, 0xbc, 0xa0, 0xa9, 0x99, 0x89, 0xfb, 0xa2, 0x47, 0xc5, 0xd5, 0x8c, 0x06, 0xfa, 0x5a, 0x82,
	0x77, 0xc6, 0x2f, 0x29, 0x53, 0x6e, 0x7f, 0xe5, 0xea, 0xec, 0x05, 0x8a, 0x98, 0xf9, 0xc6, 0xd7,
	0xbf, 0xfc, 0xf1, 0x5d, 0xea, 0x86, 0xb9, 0x6a, 0x7d, 0x79, 0xcf, 0xd2, 0xa7, 0x8a, 0x3d, 0x44,
	0x77, 0xf1, 0xe7, 0xb0, 0x2a, 0x8e, 0x8d, 0xde, 0xcb, 0x70, 0x79, 0xea, 0x85, 0x48, 0xc1, 0x54,
	0xe6, 0x5c, 0x96, 0xcc, 0x5d, 0x89, 0x50, 0xc1, 0x5b, 0xe3, 0x08, 0xd6, 0xb3, 0xd1, 0x99, 0x7e,
	0x8e, 0x3d, 0xc8, 0x8b, 0x5d, 0x8a, 0x28, 0xc3, 0x5b, 0xd3, 0xfe, 0xec, 0x0a, 0xa9, 0x3c, 0xfb,
	0xa7, 0x6f, 0xde, 0x91, 0x40, 0xb7, 0xf1, 0xee, 0x4c, 0x20, 0xeb, 0x4a, 0x23, 0xb4, 0x01, 0x2e,
	0xc9, 0x35, 0xd5, 0x95, 0xc5, 0x63, 0x41, 0x43, 0xa0, 0xcd, 0x09, 0x9b, 0x46, 0x38, 0x90, 0x08,
	0x6f, 0x99, 0xc9, 0x08, 0xa2, 0x82, 0x0c, 0x0a, 0xba, 0x0b, 0x35, 0xce, 0xe6, 0x78, 0x67, 0x86,
	0x40, 0xc5, 0x49, 0xa3, 0x46, 0x7a, 0x5f, 0x22, 0xdd, 0x2b, 0x1f, 0xcc, 0x46, 0x12, 0x97, 0x3f,
	0xeb, 0xd9, 0x58, 0x47, 0x3e, 0x17, 0xa0, 0x2f, 0x10, 0x6c, 0x8a, 0xc2, 0x4c, 0xf4, 0x3f, 0x65,
	0xb8, 0x3a, 0x67, 0x2a, 0xa8, 0x44, 0x76, 0x13, 0xe7, 0x86, 0x79, 0x5f, 0x66, 0x55, 0xc3, 0xaf,
	0x94, 0xd5, 0xe1, 0xf7, 0x08, 0x8c, 0x7a, 0xa7, 0xef, 0xb8, 0xf8, 0x3e, 0x18, 0xb2, 0x23, 0xf1,
	0x0d, 0x89, 0x35, 0xde, 0x9d, 0xe5, 0x5b, 0x35, 0xf5, 0xc8, 0xa9, 0x85, 0x8f, 0x9c, 0x5a, 0x43,
	0x3c, 0x72, 0xcc, 0x25, 0x71, 0x37, 0x7f, 0xec, 0xfa, 0x72, 0xdf, 0x8c, 0x45, 0x73, 0x36, 0xbf,
	0x07, 0x86, 0xec, 0xe4, 0x99, 0x5b, 0x95, 0xf8, 0x13, 0xdd, 0x6e, 0x2e, 0x1d, 0x3d, 0x80, 0x9d,
	0xb6, 0xd7, 0xaf, 0xb1, 0x36, 0xe9, 0x91, 0xa0, 0xa6, 0xdf, 0x6b, 0xd1, 0x93, 0x49, 0x6c, 0x39,
	0x2a, 0xc6, 0x1a, 0xf4, 0x42, 0xc4, 0xbd, 0x40, 0x57, 0x59, 0x09, 0xf0, 0xee, 0xdf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xaf, 0x38, 0xea, 0x95, 0xff, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CassandraBackupClient is the client API for CassandraBackup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CassandraBackupClient interface {
	RegisterCluster(ctx context.Context, in *ClusterRegistrationRequest, opts ...grpc.CallOption) (*ClusterRegistrationResponse, error)
	ListClusters(ctx context.Context, in *ClusterListingRequest, opts ...grpc.CallOption) (*ClusterListingResponse, error)
	ListBackups(ctx context.Context, in *BackupListingRequest, opts ...grpc.CallOption) (*BackupListingResponse, error)
	TakeBackup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error)
	RestoreBackup(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	ListRestoreStatuses(ctx context.Context, in *RestoreStatusListingRequest, opts ...grpc.CallOption) (*RestoreStatusListingResponse, error)
}

type cassandraBackupClient struct {
	cc *grpc.ClientConn
}

func NewCassandraBackupClient(cc *grpc.ClientConn) CassandraBackupClient {
	return &cassandraBackupClient{cc}
}

func (c *cassandraBackupClient) RegisterCluster(ctx context.Context, in *ClusterRegistrationRequest, opts ...grpc.CallOption) (*ClusterRegistrationResponse, error) {
	out := new(ClusterRegistrationResponse)
	err := c.cc.Invoke(ctx, "/rpc.CassandraBackup/RegisterCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cassandraBackupClient) ListClusters(ctx context.Context, in *ClusterListingRequest, opts ...grpc.CallOption) (*ClusterListingResponse, error) {
	out := new(ClusterListingResponse)
	err := c.cc.Invoke(ctx, "/rpc.CassandraBackup/ListClusters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cassandraBackupClient) ListBackups(ctx context.Context, in *BackupListingRequest, opts ...grpc.CallOption) (*BackupListingResponse, error) {
	out := new(BackupListingResponse)
	err := c.cc.Invoke(ctx, "/rpc.CassandraBackup/ListBackups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cassandraBackupClient) TakeBackup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error) {
	out := new(BackupResponse)
	err := c.cc.Invoke(ctx, "/rpc.CassandraBackup/TakeBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cassandraBackupClient) RestoreBackup(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, "/rpc.CassandraBackup/RestoreBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cassandraBackupClient) ListRestoreStatuses(ctx context.Context, in *RestoreStatusListingRequest, opts ...grpc.CallOption) (*RestoreStatusListingResponse, error) {
	out := new(RestoreStatusListingResponse)
	err := c.cc.Invoke(ctx, "/rpc.CassandraBackup/ListRestoreStatuses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CassandraBackupServer is the server API for CassandraBackup service.
type CassandraBackupServer interface {
	RegisterCluster(context.Context, *ClusterRegistrationRequest) (*ClusterRegistrationResponse, error)
	ListClusters(context.Context, *ClusterListingRequest) (*ClusterListingResponse, error)
	ListBackups(context.Context, *BackupListingRequest) (*BackupListingResponse, error)
	TakeBackup(context.Context, *BackupRequest) (*BackupResponse, error)
	RestoreBackup(context.Context, *RestoreRequest) (*RestoreResponse, error)
	ListRestoreStatuses(context.Context, *RestoreStatusListingRequest) (*RestoreStatusListingResponse, error)
}

// UnimplementedCassandraBackupServer can be embedded to have forward compatible implementations.
type UnimplementedCassandraBackupServer struct {
}

func (*UnimplementedCassandraBackupServer) RegisterCluster(ctx context.Context, req *ClusterRegistrationRequest) (*ClusterRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterCluster not implemented")
}
func (*UnimplementedCassandraBackupServer) ListClusters(ctx context.Context, req *ClusterListingRequest) (*ClusterListingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListClusters not implemented")
}
func (*UnimplementedCassandraBackupServer) ListBackups(ctx context.Context, req *BackupListingRequest) (*BackupListingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBackups not implemented")
}
func (*UnimplementedCassandraBackupServer) TakeBackup(ctx context.Context, req *BackupRequest) (*BackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TakeBackup not implemented")
}
func (*UnimplementedCassandraBackupServer) RestoreBackup(ctx context.Context, req *RestoreRequest) (*RestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreBackup not implemented")
}
func (*UnimplementedCassandraBackupServer) ListRestoreStatuses(ctx context.Context, req *RestoreStatusListingRequest) (*RestoreStatusListingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRestoreStatuses not implemented")
}

func RegisterCassandraBackupServer(s *grpc.Server, srv CassandraBackupServer) {
	s.RegisterService(&_CassandraBackup_serviceDesc, srv)
}

func _CassandraBackup_RegisterCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CassandraBackupServer).RegisterCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.CassandraBackup/RegisterCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CassandraBackupServer).RegisterCluster(ctx, req.(*ClusterRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CassandraBackup_ListClusters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CassandraBackupServer).ListClusters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.CassandraBackup/ListClusters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CassandraBackupServer).ListClusters(ctx, req.(*ClusterListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CassandraBackup_ListBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CassandraBackupServer).ListBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.CassandraBackup/ListBackups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CassandraBackupServer).ListBackups(ctx, req.(*BackupListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CassandraBackup_TakeBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CassandraBackupServer).TakeBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.CassandraBackup/TakeBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CassandraBackupServer).TakeBackup(ctx, req.(*BackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CassandraBackup_RestoreBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CassandraBackupServer).RestoreBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.CassandraBackup/RestoreBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CassandraBackupServer).RestoreBackup(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CassandraBackup_ListRestoreStatuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreStatusListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CassandraBackupServer).ListRestoreStatuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.CassandraBackup/ListRestoreStatuses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CassandraBackupServer).ListRestoreStatuses(ctx, req.(*RestoreStatusListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CassandraBackup_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.CassandraBackup",
	HandlerType: (*CassandraBackupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterCluster",
			Handler:    _CassandraBackup_RegisterCluster_Handler,
		},
		{
			MethodName: "ListClusters",
			Handler:    _CassandraBackup_ListClusters_Handler,
		},
		{
			MethodName: "ListBackups",
			Handler:    _CassandraBackup_ListBackups_Handler,
		},
		{
			MethodName: "TakeBackup",
			Handler:    _CassandraBackup_TakeBackup_Handler,
		},
		{
			MethodName: "RestoreBackup",
			Handler:    _CassandraBackup_RestoreBackup_Handler,
		},
		{
			MethodName: "ListRestoreStatuses",
			Handler:    _CassandraBackup_ListRestoreStatuses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/main/proto/cassandra-backup.proto",
}

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminClient interface {
	Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Unpause(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	Stats(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StatsResponse, error)
}

type adminClient struct {
	cc *grpc.ClientConn
}

func NewAdminClient(cc *grpc.ClientConn) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/rpc.Admin/Pause", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) Unpause(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/rpc.Admin/Unpause", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) Stats(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, "/rpc.Admin/Stats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
type AdminServer interface {
	Pause(context.Context, *PauseRequest) (*empty.Empty, error)
	Unpause(context.Context, *empty.Empty) (*empty.Empty, error)
	Stats(context.Context, *empty.Empty) (*StatsResponse, error)
}

// UnimplementedAdminServer can be embedded to have forward compatible implementations.
type UnimplementedAdminServer struct {
}

func (*UnimplementedAdminServer) Pause(ctx context.Context, req *PauseRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pause not implemented")
}
func (*UnimplementedAdminServer) Unpause(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unpause not implemented")
}
func (*UnimplementedAdminServer) Stats(ctx context.Context, req *empty.Empty) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}

func RegisterAdminServer(s *grpc.Server, srv AdminServer) {
	s.RegisterService(&_Admin_serviceDesc, srv)
}

func _Admin_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Admin/Pause",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).Pause(ctx, req.(*PauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_Unpause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).Unpause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Admin/Unpause",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).Unpause(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Admin/Stats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).Stats(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Admin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pause",
			Handler:    _Admin_Pause_Handler,
		},
		{
			MethodName: "Unpause",
			Handler:    _Admin_Unpause_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _Admin_Stats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/main/proto/cassandra-backup.proto",
}
