// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cassandra-backup.proto

package com.scalar.backup.cassandra.rpc;

public interface BackupRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.BackupRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cluster_id = 1;</code>
   */
  java.lang.String getClusterId();
  /**
   * <code>string cluster_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getClusterIdBytes();

  /**
   * <code>uint32 backup_type = 2;</code>
   */
  int getBackupType();

  /**
   * <code>string target_ip = 3;</code>
   */
  java.lang.String getTargetIp();
  /**
   * <code>string target_ip = 3;</code>
   */
  com.google.protobuf.ByteString
      getTargetIpBytes();

  /**
   * <code>repeated string keyspaces = 4;</code>
   */
  java.util.List<java.lang.String>
      getKeyspacesList();
  /**
   * <code>repeated string keyspaces = 4;</code>
   */
  int getKeyspacesCount();
  /**
   * <code>repeated string keyspaces = 4;</code>
   */
  java.lang.String getKeyspaces(int index);
  /**
   * <code>repeated string keyspaces = 4;</code>
   */
  com.google.protobuf.ByteString
      getKeyspacesBytes(int index);

  /**
   * <code>string snapshot_id = 5;</code>
   */
  java.lang.String getSnapshotId();
  /**
   * <code>string snapshot_id = 5;</code>
   */
  com.google.protobuf.ByteString
      getSnapshotIdBytes();
}
