// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cassandra-backup.proto

package com.scalar.backup.cassandra.rpc;

public interface RestoreRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.RestoreRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cluster_id = 1;</code>
   */
  java.lang.String getClusterId();
  /**
   * <code>string cluster_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getClusterIdBytes();

  /**
   * <code>string backup_id = 2;</code>
   */
  java.lang.String getBackupId();
  /**
   * <code>string backup_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getBackupIdBytes();

  /**
   * <code>uint32 restore_type = 3;</code>
   */
  int getRestoreType();

  /**
   * <code>repeated string target_ips = 4;</code>
   */
  java.util.List<java.lang.String>
      getTargetIpsList();
  /**
   * <code>repeated string target_ips = 4;</code>
   */
  int getTargetIpsCount();
  /**
   * <code>repeated string target_ips = 4;</code>
   */
  java.lang.String getTargetIps(int index);
  /**
   * <code>repeated string target_ips = 4;</code>
   */
  com.google.protobuf.ByteString
      getTargetIpsBytes(int index);
}
