// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cassy.proto

package com.scalar.cassy.rpc;

/**
 * Protobuf enum {@code rpc.OperationStatus}
 */
public enum OperationStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN = 0;</code>
   */
  UNKNOWN(0),
  /**
   * <code>INITIALIZED = 1;</code>
   */
  INITIALIZED(1),
  /**
   * <code>STARTED = 2;</code>
   */
  STARTED(2),
  /**
   * <code>COMPLETED = 3;</code>
   */
  COMPLETED(3),
  /**
   * <code>FAILED = 4;</code>
   */
  FAILED(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN = 0;</code>
   */
  public static final int UNKNOWN_VALUE = 0;
  /**
   * <code>INITIALIZED = 1;</code>
   */
  public static final int INITIALIZED_VALUE = 1;
  /**
   * <code>STARTED = 2;</code>
   */
  public static final int STARTED_VALUE = 2;
  /**
   * <code>COMPLETED = 3;</code>
   */
  public static final int COMPLETED_VALUE = 3;
  /**
   * <code>FAILED = 4;</code>
   */
  public static final int FAILED_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OperationStatus valueOf(int value) {
    return forNumber(value);
  }

  public static OperationStatus forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN;
      case 1: return INITIALIZED;
      case 2: return STARTED;
      case 3: return COMPLETED;
      case 4: return FAILED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OperationStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OperationStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OperationStatus>() {
          public OperationStatus findValueByNumber(int number) {
            return OperationStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.scalar.cassy.rpc.CassyProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final OperationStatus[] VALUES = values();

  public static OperationStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OperationStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:rpc.OperationStatus)
}

